CREATE TABLE [dbo].[Party]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[PartyTypeId] UNIQUEIDENTIFIER NOT NULL,
	[SourceOfIntroduction] NVARCHAR(255) NOT NULL,
	[Created] DATETIME2 NOT NULL,
	[CreatedBy] NVARCHAR(255) NOT NULL,
	[Modified] DATETIME2 NULL,
	[ModifiedBy] NVARCHAR(255) NULL,
	CONSTRAINT [PK_Party] PRIMARY KEY CLUSTERED 
	(
		[Id]
	) 
)
GO

ALTER TABLE [dbo].[Party] ADD CONSTRAINT [FK_Party_PartyType] FOREIGN KEY([PartyTypeId])
REFERENCES [dbo].[PartyType] ([Id])
GO

ALTER TABLE [dbo].[Party] CHECK CONSTRAINT [FK_Party_PartyType]
GO

ALTER TABLE [dbo].[Party]
ADD CONSTRAINT [DF_Party_Created] DEFAULT (GETUTCDATE()) FOR [Created];
GO
