//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1234.0 using the following command:
// xscgen ./ConsoleApp1/RP14A.xsd -n ConsoleApp1

namespace GovUk.Forms.IPUpload.Domain;

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("YesNoType", Namespace="www.inss.gsi.gov.uk/RP14A_Application")]
public enum YesNoType
{
    
    Yes,
    
    No,
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("NameType", Namespace="www.inss.gsi.gov.uk/RP14A_Application")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class NameType
{
    
    [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
    [System.Xml.Serialization.XmlElementAttribute("Surname")]
    public string Surname { get; set; }
    
    [System.Xml.Serialization.XmlElementAttribute("Forenames")]
    public string Forenames { get; set; }
    
    [System.Xml.Serialization.XmlElementAttribute("Title")]
    public string Title { get; set; }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("PeriodType", Namespace="www.inss.gsi.gov.uk/RP14A_Application")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PeriodType
{
    
    [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
    [System.Xml.Serialization.XmlElementAttribute("StartDate", DataType="date")]
    public System.DateTime StartDate { get; set; }
    
    [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
    [System.Xml.Serialization.XmlElementAttribute("EndDate", DataType="date")]
    public System.DateTime EndDate { get; set; }
}

/// <summary>
/// <para>Comment describing your root element</para>
/// </summary>
[System.ComponentModel.DescriptionAttribute("Comment describing your root element")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("RP14A", Namespace="www.inss.gsi.gov.uk/RP14A_Application", AnonymousType=true)]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("RP14A", Namespace="www.inss.gsi.gov.uk/RP14A_Application")]
public partial class Rp14A
{
    
    [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
    [System.Xml.Serialization.XmlElementAttribute("Header")]
    public Rp14AHeader Header { get; set; }
    
    [System.Xml.Serialization.XmlElementAttribute("EmployerName")]
    public string EmployerName { get; set; }
    
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    private System.Collections.ObjectModel.Collection<Rp14AEmployee> _employee;
    
    [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
    [System.Xml.Serialization.XmlElementAttribute("Employee")]
    public System.Collections.ObjectModel.Collection<Rp14AEmployee> Employee
    {
        get
        {
            return _employee;
        }
        private set
        {
            _employee = value;
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Initializes a new instance of the <see cref="Rp14A" /> class.</para>
    /// </summary>
    public Rp14A()
    {
        this._employee = new System.Collections.ObjectModel.Collection<Rp14AEmployee>();
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("Rp14AHeader", Namespace="www.inss.gsi.gov.uk/RP14A_Application", AnonymousType=true)]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Rp14AHeader
{
    
    /// <summary>
    /// <para>Case Reference to which this document relates.</para>
    /// <para xml:lang="en">Pattern: CN[0-9]{8}|cn[0-9]{8}|Cn[0-9]{8}|cN[0-9]{8}.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Case Reference to which this document relates.")]
    [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("CN[0-9]{8}|cn[0-9]{8}|Cn[0-9]{8}|cN[0-9]{8}")]
    [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
    [System.Xml.Serialization.XmlElementAttribute("CaseReference")]
    public string CaseReference { get; set; }
    
    /// <summary>
    /// <para>The DMS document ID to which this document relates.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("The DMS document ID to which this document relates.")]
    [System.Xml.Serialization.XmlElementAttribute("DMSDocumentID")]
    public string DmsDocumentId { get; set; }
    
    /// <summary>
    /// <para>Claim Reference to which this document relates.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Claim Reference to which this document relates.")]
    [System.Xml.Serialization.XmlElementAttribute("ClaimReference")]
    public string ClaimReference { get; set; }
    
    [System.Xml.Serialization.XmlElementAttribute("CHAMPDocumentID")]
    public string ChampDocumentId { get; set; }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("Rp14AEmployee", Namespace="www.inss.gsi.gov.uk/RP14A_Application", AnonymousType=true)]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Rp14AEmployee
{
    
    [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
    [System.Xml.Serialization.XmlElementAttribute("EmployeeName")]
    public NameType EmployeeName { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Maximum length: 1.</para>
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1)]
    [System.Xml.Serialization.XmlElementAttribute("NIClass")]
    public string NiClass { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Pattern: [A-CEGHJ-PR-TW-Za-ceghj-pr-tw-z]{1}[A-CEGHJ-NPR-TW-Za-ceghj-npr-tw-z]{1}[0-9]{6}[A-DFMa-dfm]{1}.</para>
    /// </summary>
    [System.ComponentModel.DataAnnotations.RegularExpressionAttribute(("[A-CEGHJ-PR-TW-Za-ceghj-pr-tw-z]{1}[A-CEGHJ-NPR-TW-Za-ceghj-npr-tw-z]{1}[0-9]{6}[" +
        "A-DFMa-dfm]{1}"))]
    [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
    [System.Xml.Serialization.XmlElementAttribute("NINO")]
    public string Nino { get; set; }
    
    [System.Xml.Serialization.XmlElementAttribute("DateOfBirth", DataType="date")]
    public System.DateTime DateOfBirth { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the DateOfBirth property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DateOfBirthSpecified { get; set; }
    
    [System.Xml.Serialization.XmlElementAttribute("StartDate", DataType="date")]
    public System.DateTime StartDate { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the StartDate property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StartDateSpecified { get; set; }
    
    [System.Xml.Serialization.XmlElementAttribute("DateNoticeGiven", DataType="date")]
    public System.DateTime DateNoticeGiven { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the DateNoticeGiven property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DateNoticeGivenSpecified { get; set; }
    
    [System.Xml.Serialization.XmlElementAttribute("EndDate", DataType="date")]
    public System.DateTime EndDate { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the EndDate property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EndDateSpecified { get; set; }
    
    [System.Xml.Serialization.XmlElementAttribute("IsDirector")]
    public YesNoType IsDirector { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the IsDirector property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsDirectorSpecified { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Total number of digits in fraction: 1.</para>
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute("AverageHoursWorked")]
    public decimal AverageHoursWorked { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the AverageHoursWorked property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AverageHoursWorkedSpecified { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute("MoneyOwedToEmployer")]
    public decimal MoneyOwedToEmployer { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the MoneyOwedToEmployer property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MoneyOwedToEmployerSpecified { get; set; }
    
    [System.Xml.Serialization.XmlElementAttribute("EntitledToRedundancyPay")]
    public YesNoType EntitledToRedundancyPay { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the EntitledToRedundancyPay property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EntitledToRedundancyPaySpecified { get; set; }
    
    [System.Xml.Serialization.XmlElementAttribute("EntitledToNoticePay")]
    public YesNoType EntitledToNoticePay { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the EntitledToNoticePay property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EntitledToNoticePaySpecified { get; set; }
    
    [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
    [System.Xml.Serialization.XmlElementAttribute("PayDetails")]
    public Rp14AEmployeePayDetails PayDetails { get; set; }
    
    [System.Xml.Serialization.XmlElementAttribute("Holiday")]
    public Rp14AEmployeeHoliday Holiday { get; set; }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("Rp14AEmployeePayDetails", Namespace="www.inss.gsi.gov.uk/RP14A_Application", AnonymousType=true)]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Rp14AEmployeePayDetails
{
    
    /// <summary>
    /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute("BasicPayPerWeek")]
    public decimal BasicPayPerWeek { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the BasicPayPerWeek property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BasicPayPerWeekSpecified { get; set; }
    
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    private System.Collections.ObjectModel.Collection<Rp14AEmployeePayDetailsComponentPayPerWeek> _componentPayPerWeek;
    
    /// <summary>
    /// <para>Override for base pay when calculating a component rate.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Override for base pay when calculating a component rate.")]
    [System.Xml.Serialization.XmlElementAttribute("ComponentPayPerWeek")]
    public System.Collections.ObjectModel.Collection<Rp14AEmployeePayDetailsComponentPayPerWeek> ComponentPayPerWeek
    {
        get
        {
            return _componentPayPerWeek;
        }
        private set
        {
            _componentPayPerWeek = value;
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Gets a value indicating whether the ComponentPayPerWeek collection is empty.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ComponentPayPerWeekSpecified
    {
        get
        {
            return (this.ComponentPayPerWeek.Count != 0);
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Initializes a new instance of the <see cref="Rp14AEmployeePayDetails" /> class.</para>
    /// </summary>
    public Rp14AEmployeePayDetails()
    {
        this._componentPayPerWeek = new System.Collections.ObjectModel.Collection<Rp14AEmployeePayDetailsComponentPayPerWeek>();
        this._arrearsOfPay = new System.Collections.ObjectModel.Collection<Rp14AEmployeePayDetailsArrearsOfPayArrearsOfPayPeriod>();
    }
    
    /// <summary>
    /// <para>Pay day, if paid weekly.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Pay day, if paid weekly.")]
    [System.Xml.Serialization.XmlElementAttribute("WeeklyPayDay")]
    public Rp14AEmployeePayDetailsWeeklyPayDay WeeklyPayDay { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the WeeklyPayDay property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WeeklyPayDaySpecified { get; set; }
    
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    private System.Collections.ObjectModel.Collection<Rp14AEmployeePayDetailsArrearsOfPayArrearsOfPayPeriod> _arrearsOfPay;
    
    [System.Xml.Serialization.XmlArrayAttribute("ArrearsOfPay")]
    [System.Xml.Serialization.XmlArrayItemAttribute("ArrearsOfPayPeriod", Namespace="www.inss.gsi.gov.uk/RP14A_Application")]
    public System.Collections.ObjectModel.Collection<Rp14AEmployeePayDetailsArrearsOfPayArrearsOfPayPeriod> ArrearsOfPay
    {
        get
        {
            return _arrearsOfPay;
        }
        private set
        {
            _arrearsOfPay = value;
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Gets a value indicating whether the ArrearsOfPay collection is empty.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ArrearsOfPaySpecified
    {
        get
        {
            return (this.ArrearsOfPay.Count != 0);
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("Rp14AEmployeePayDetailsComponentPayPerWeek", Namespace="www.inss.gsi.gov.uk/RP14A_Application", AnonymousType=true)]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Rp14AEmployeePayDetailsComponentPayPerWeek
{
    
    [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
    [System.Xml.Serialization.XmlElementAttribute("ComponentType")]
    public Rp14AEmployeePayDetailsComponentPayPerWeekComponentType ComponentType { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute("ComponentRate")]
    public string ComponentRate { get; set; }
    
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    private Rp14AEmployeePayDetailsComponentPayPerWeekComponentRateStatus _componentRateStatus = Rp14AEmployeePayDetailsComponentPayPerWeekComponentRateStatus.RateProvided;
    
    /// <summary>
    /// <para>If the component rate is available, and if not, why.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("If the component rate is available, and if not, why.")]
    [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
    [System.Xml.Serialization.XmlElementAttribute("ComponentRateStatus")]
    public Rp14AEmployeePayDetailsComponentPayPerWeekComponentRateStatus ComponentRateStatus
    {
        get
        {
            return _componentRateStatus;
        }
        set
        {
            _componentRateStatus = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("Rp14AEmployeePayDetailsComponentPayPerWeekComponentType", Namespace="www.inss.gsi.gov.uk/RP14A_Application", AnonymousType=true)]
public enum Rp14AEmployeePayDetailsComponentPayPerWeekComponentType
{
    
    [System.Xml.Serialization.XmlEnumAttribute("Redundancy Pay")]
    RedundancyPay,
    
    [System.Xml.Serialization.XmlEnumAttribute("Arrears of Pay")]
    ArrearsOfPay,
    
    [System.Xml.Serialization.XmlEnumAttribute("Holiday Pay Taken Not Paid")]
    HolidayPayTakenNotPaid,
    
    [System.Xml.Serialization.XmlEnumAttribute("Holiday Pay Accrued")]
    HolidayPayAccrued,
    
    [System.Xml.Serialization.XmlEnumAttribute("Protective Award")]
    ProtectiveAward,
    
    [System.Xml.Serialization.XmlEnumAttribute("Compensatory Notice Pay")]
    CompensatoryNoticePay,
    
    [System.Xml.Serialization.XmlEnumAttribute("Refund of Notional Tax")]
    RefundOfNotionalTax,
    
    [System.Xml.Serialization.XmlEnumAttribute("Basic Award")]
    BasicAward,
    
    [System.Xml.Serialization.XmlEnumAttribute("Notice Worked Not Paid")]
    NoticeWorkedNotPaid,
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("Rp14AEmployeePayDetailsComponentPayPerWeekComponentRateStatus", Namespace="www.inss.gsi.gov.uk/RP14A_Application", AnonymousType=true)]
public enum Rp14AEmployeePayDetailsComponentPayPerWeekComponentRateStatus
{
    
    [System.Xml.Serialization.XmlEnumAttribute("Rate provided")]
    RateProvided,
    
    [System.Xml.Serialization.XmlEnumAttribute("No rate defined in law")]
    NoRateDefinedInLaw,
    
    [System.Xml.Serialization.XmlEnumAttribute("Data not yet available")]
    DataNotYetAvailable,
    
    [System.Xml.Serialization.XmlEnumAttribute("Data to be requested from IP")]
    DataToBeRequestedFromIp,
    
    [System.Xml.Serialization.XmlEnumAttribute("Fixed rate of pay")]
    FixedRateOfPay,
    
    [System.Xml.Serialization.XmlEnumAttribute("No holiday pay payable")]
    NoHolidayPayPayable,
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("Rp14AEmployeePayDetailsWeeklyPayDay", Namespace="www.inss.gsi.gov.uk/RP14A_Application", AnonymousType=true)]
public enum Rp14AEmployeePayDetailsWeeklyPayDay
{
    
    Sunday,
    
    Monday,
    
    Tuesday,
    
    Wednesday,
    
    Thursday,
    
    Friday,
    
    Saturday,
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("Rp14AEmployeePayDetailsArrearsOfPay", Namespace="www.inss.gsi.gov.uk/RP14A_Application", AnonymousType=true)]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Rp14AEmployeePayDetailsArrearsOfPay
{
    
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    private System.Collections.ObjectModel.Collection<Rp14AEmployeePayDetailsArrearsOfPayArrearsOfPayPeriod> _arrearsOfPayPeriod;
    
    [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
    [System.Xml.Serialization.XmlElementAttribute("ArrearsOfPayPeriod")]
    public System.Collections.ObjectModel.Collection<Rp14AEmployeePayDetailsArrearsOfPayArrearsOfPayPeriod> ArrearsOfPayPeriod
    {
        get
        {
            return _arrearsOfPayPeriod;
        }
        private set
        {
            _arrearsOfPayPeriod = value;
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Initializes a new instance of the <see cref="Rp14AEmployeePayDetailsArrearsOfPay" /> class.</para>
    /// </summary>
    public Rp14AEmployeePayDetailsArrearsOfPay()
    {
        this._arrearsOfPayPeriod = new System.Collections.ObjectModel.Collection<Rp14AEmployeePayDetailsArrearsOfPayArrearsOfPayPeriod>();
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("Rp14AEmployeePayDetailsArrearsOfPayArrearsOfPayPeriod", Namespace="www.inss.gsi.gov.uk/RP14A_Application", AnonymousType=true)]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Rp14AEmployeePayDetailsArrearsOfPayArrearsOfPayPeriod
{
    
    [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
    [System.Xml.Serialization.XmlElementAttribute("Period")]
    public PeriodType Period { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute("AOPOwed")]
    public decimal AopOwed { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the AopOwed property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AopOwedSpecified { get; set; }
    
    [System.Xml.Serialization.XmlElementAttribute("PayType")]
    public Rp14AEmployeePayDetailsArrearsOfPayArrearsOfPayPeriodPayType PayType { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the PayType property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PayTypeSpecified { get; set; }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("Rp14AEmployeePayDetailsArrearsOfPayArrearsOfPayPeriodPayType", Namespace="www.inss.gsi.gov.uk/RP14A_Application", AnonymousType=true)]
public enum Rp14AEmployeePayDetailsArrearsOfPayArrearsOfPayPeriodPayType
{
    
    [System.Xml.Serialization.XmlEnumAttribute("wages")]
    Wages,
    
    [System.Xml.Serialization.XmlEnumAttribute("bouncedcheque")]
    Bouncedcheque,
    
    [System.Xml.Serialization.XmlEnumAttribute("attachmentofearnings")]
    Attachmentofearnings,
    
    [System.Xml.Serialization.XmlEnumAttribute("overtime")]
    Overtime,
    
    [System.Xml.Serialization.XmlEnumAttribute("commission")]
    Commission,
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("Rp14AEmployeeHoliday", Namespace="www.inss.gsi.gov.uk/RP14A_Application", AnonymousType=true)]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Rp14AEmployeeHoliday
{
    
    [System.Xml.Serialization.XmlElementAttribute("HolidayYearStart", DataType="date")]
    public System.DateTime HolidayYearStart { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the HolidayYearStart property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HolidayYearStartSpecified { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Total number of digits in fraction: 1.</para>
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute("HolidayContractedEntitlementDays")]
    public decimal HolidayContractedEntitlementDays { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the HolidayContractedEntitlementDays property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HolidayContractedEntitlementDaysSpecified { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Total number of digits in fraction: 1.</para>
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute("HolidayDaysCarriedForward")]
    public decimal HolidayDaysCarriedForward { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the HolidayDaysCarriedForward property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HolidayDaysCarriedForwardSpecified { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Total number of digits in fraction: 1.</para>
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute("HolidayDaysTaken")]
    public decimal HolidayDaysTaken { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the HolidayDaysTaken property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HolidayDaysTakenSpecified { get; set; }
    
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    private System.Collections.ObjectModel.Collection<PeriodType> _holidayNotPaid;
    
    /// <summary>
    /// <para>Holiday taken but not paid</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Holiday taken but not paid")]
    [System.Xml.Serialization.XmlArrayAttribute("HolidayNotPaid")]
    [System.Xml.Serialization.XmlArrayItemAttribute("Holiday", Namespace="www.inss.gsi.gov.uk/RP14A_Application")]
    public System.Collections.ObjectModel.Collection<PeriodType> HolidayNotPaid
    {
        get
        {
            return _holidayNotPaid;
        }
        private set
        {
            _holidayNotPaid = value;
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Gets a value indicating whether the HolidayNotPaid collection is empty.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HolidayNotPaidSpecified
    {
        get
        {
            return (this.HolidayNotPaid.Count != 0);
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Initializes a new instance of the <see cref="Rp14AEmployeeHoliday" /> class.</para>
    /// </summary>
    public Rp14AEmployeeHoliday()
    {
        this._holidayNotPaid = new System.Collections.ObjectModel.Collection<PeriodType>();
    }
    
    /// <summary>
    /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute("NoDaysHolidayOwed")]
    public decimal NoDaysHolidayOwed { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the NoDaysHolidayOwed property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NoDaysHolidayOwedSpecified { get; set; }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("Rp14AEmployeeHolidayHolidayNotPaid", Namespace="www.inss.gsi.gov.uk/RP14A_Application", AnonymousType=true)]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Rp14AEmployeeHolidayHolidayNotPaid
{
    
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    private System.Collections.ObjectModel.Collection<PeriodType> _holiday;
    
    [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
    [System.Xml.Serialization.XmlElementAttribute("Holiday")]
    public System.Collections.ObjectModel.Collection<PeriodType> Holiday
    {
        get
        {
            return _holiday;
        }
        private set
        {
            _holiday = value;
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Initializes a new instance of the <see cref="Rp14AEmployeeHolidayHolidayNotPaid" /> class.</para>
    /// </summary>
    public Rp14AEmployeeHolidayHolidayNotPaid()
    {
        this._holiday = new System.Collections.ObjectModel.Collection<PeriodType>();
    }
}
