// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace GovUk.Forms.HostApp.UI.Test.Features.Validation
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Employee Validation")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("MEDS-1067")]
    public partial class EmployeeValidationFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "MEDS-1067"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Validation", "Employee Validation", "              As an Insolvency Practitioner user\r\n              I want RP14A vali" +
                "dation to run before submission to Dynamics\r\n  So that I can fix errors immediat" +
                "ely and avoid delayed rejection", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "EmployeeValidation.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
        #line hidden
#line 9
            await testRunner.GivenAsync("I am on the upload page as a \"Admin\" user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Validation/EmployeeValidation.feature.ndjson", 12);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("RP14A Display error for missing employee surname")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("allure.subSuite:Employee")]
        public async global::System.Threading.Tasks.Task RP14ADisplayErrorForMissingEmployeeSurname()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "allure.subSuite:Employee"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RP14A Display error for missing employee surname", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
        await this.FeatureBackgroundAsync();
#line hidden
#line 13
            await testRunner.GivenAsync("the RP14A contains an employee with no surname", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
             await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
             await testRunner.ThenAsync("I should see the validation error \"1 missing employee surname\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
              await testRunner.AndAsync("I should be able to view employee error details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Return to the upload page after attempting to submit an invalid RP14A")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("visual")]
        [global::NUnit.Framework.CategoryAttribute("allure.subSuite:Employee")]
        public async global::System.Threading.Tasks.Task ReturnToTheUploadPageAfterAttemptingToSubmitAnInvalidRP14A()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "visual",
                    "allure.subSuite:Employee"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Return to the upload page after attempting to submit an invalid RP14A", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 20
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
        await this.FeatureBackgroundAsync();
#line hidden
#line 21
             await testRunner.GivenAsync("the RP14A contains an employee with no surname", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 22
             await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 23
              await testRunner.AndAsync("I proceed to the check answers page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
             await testRunner.ThenAsync("I should be returned to the upload page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("RP14A Display error when employee surname is longer than 99 characters")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("allure.subSuite:Employee")]
        public async global::System.Threading.Tasks.Task RP14ADisplayErrorWhenEmployeeSurnameIsLongerThan99Characters()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "allure.subSuite:Employee"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RP14A Display error when employee surname is longer than 99 characters", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 28
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
        await this.FeatureBackgroundAsync();
#line hidden
#line 29
            await testRunner.GivenAsync("the RP14A contains an employee surname longer than 99 characters", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 30
             await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 31
             await testRunner.ThenAsync("I should see the validation error \"1 invalid length of the employee surname\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 32
              await testRunner.AndAsync("I should be able to view employee error details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("RP14A Display error for missing employee national insurance number")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("allure.subSuite:NationalInsurance")]
        [global::NUnit.Framework.CategoryAttribute("bug")]
        public async global::System.Threading.Tasks.Task RP14ADisplayErrorForMissingEmployeeNationalInsuranceNumber()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "allure.subSuite:NationalInsurance",
                    "bug"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RP14A Display error for missing employee national insurance number", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 35
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
        await this.FeatureBackgroundAsync();
#line hidden
#line 36
            await testRunner.GivenAsync("the RP14A contains an employee with no national insurance number", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 37
             await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 38
             await testRunner.ThenAsync("I should see the national insurance number validation error \"[COUNT] missing the " +
                        "employee national insurance number\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 39
              await testRunner.AndAsync("I should be able to view national insurance number error details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("RP14A Display error for invalid employee national insurance number format")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("allure.subSuite:NationalInsurance")]
        [global::NUnit.Framework.CategoryAttribute("addVideo")]
        [global::NUnit.Framework.TestCaseAttribute("123456789", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("AB12345C", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("QQ123456A", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("AB123456Z", "7", null)]
        public async global::System.Threading.Tasks.Task RP14ADisplayErrorForInvalidEmployeeNationalInsuranceNumberFormat(string nationalInsuranceNumber, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "allure.subSuite:NationalInsurance",
                    "addVideo"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("nationalInsuranceNumber", nationalInsuranceNumber);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RP14A Display error for invalid employee national insurance number format", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 42
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
        await this.FeatureBackgroundAsync();
#line hidden
#line 43
            await testRunner.GivenAsync(string.Format("the RP14A contains employee national insurance number \"{0}\"", nationalInsuranceNumber), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 44
             await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
             await testRunner.ThenAsync("I should see the national insurance number validation error \"1 invalid employee n" +
                        "ational insurance number format\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 46
              await testRunner.AndAsync("I should be able to view national insurance number error details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("RP14A Display error when employment start date is after employment end date")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("allure.story:Employee")]
        [global::NUnit.Framework.CategoryAttribute("bug")]
        public async global::System.Threading.Tasks.Task RP14ADisplayErrorWhenEmploymentStartDateIsAfterEmploymentEndDate()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "allure.story:Employee",
                    "bug"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RP14A Display error when employment start date is after employment end date", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 56
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
        await this.FeatureBackgroundAsync();
#line hidden
#line 57
            await testRunner.GivenAsync("the RP14A contains employment start date \"2026-04-30\" with end date \"2026-04-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 58
             await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Message",
                            "Hint",
                            "Type"});
                table1.AddRow(new string[] {
                            "1 invalid employment dates for the employee",
                            "Start date must be before the end date",
                            "Employee employment dates"});
#line 59
             await testRunner.ThenAsync("I should see the following validation errors", ((string)(null)), table1, "Then ");
#line hidden
#line 62
              await testRunner.AndAsync("I should be able to view the employee employment dates error details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
              await testRunner.AndAsync("I should be able to go to the previous page from the error details page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("RP14A Display aggregated count for repeated employee surname errors")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("allure.subSuite:Employee")]
        [global::NUnit.Framework.CategoryAttribute("addVideo")]
        public async global::System.Threading.Tasks.Task RP14ADisplayAggregatedCountForRepeatedEmployeeSurnameErrors()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "allure.subSuite:Employee",
                    "addVideo"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RP14A Display aggregated count for repeated employee surname errors", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 67
         this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
        await this.FeatureBackgroundAsync();
#line hidden
#line 68
            await testRunner.GivenAsync("the RP14A contains 3 employees with no surname", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 69
             await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 70
             await testRunner.ThenAsync("I should see the validation error \"3 missing employee surname\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 71
             await testRunner.AndAsync("I should be able to view the validation error details for employees where the sur" +
                        "name is missing", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
