// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace GovUk.Forms.HostApp.UI.Test.Features.Validation
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Employee Validation")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class EmployeeValidationFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Validation", "Employee Validation", "              As an Insolvency Practitioner user\r\n              I want RP14A vali" +
                "dation to run before submission to Dynamics\r\n  So that I can fix errors immediat" +
                "ely and avoid delayed rejection", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "EmployeeValidation.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
        #line hidden
#line 8
            await testRunner.GivenAsync("I am on the upload page as a \"Admin\" user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Validation/EmployeeValidation.feature.ndjson", 21);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("RP14A Display error for missing employee surname")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("allure.subSuite:Employee")]
        public async global::System.Threading.Tasks.Task RP14ADisplayErrorForMissingEmployeeSurname()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "allure.subSuite:Employee"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RP14A Display error for missing employee surname", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
        await this.FeatureBackgroundAsync();
#line hidden
#line 12
            await testRunner.GivenAsync("the RP14A contains an employee with no surname", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 13
             await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
             await testRunner.ThenAsync("I should see the validation error \"1 missing employee surname\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 15
              await testRunner.AndAsync("I should be able to view employee error details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Return to upload page when proceeding after submission with errors")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("visual")]
        [global::NUnit.Framework.CategoryAttribute("allure.subSuite:Employee")]
        public async global::System.Threading.Tasks.Task ReturnToUploadPageWhenProceedingAfterSubmissionWithErrors()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "visual",
                    "allure.subSuite:Employee"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Return to upload page when proceeding after submission with errors", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
        await this.FeatureBackgroundAsync();
#line hidden
#line 20
              await testRunner.AndAsync("the RP14A contains an employee with no surname", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
             await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
              await testRunner.AndAsync("I proceed to the check answers page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
             await testRunner.ThenAsync("I should be returned to the upload page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("RP14A Display error when employee surname is longer than 99 characters")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("allure.subSuite:Employee")]
        public async global::System.Threading.Tasks.Task RP14ADisplayErrorWhenEmployeeSurnameIsLongerThan99Characters()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "allure.subSuite:Employee"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RP14A Display error when employee surname is longer than 99 characters", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
        await this.FeatureBackgroundAsync();
#line hidden
#line 28
            await testRunner.GivenAsync("the RP14A contains an employee surname longer than 99 characters", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 29
             await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
             await testRunner.ThenAsync("I should see the validation error \"1 invalid length of the employee surname\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 31
              await testRunner.AndAsync("I should be able to view employee error details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("RP14A Display error for invalid arrears of pay owed format")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("allure.subSuite:Payment")]
        [global::NUnit.Framework.TestCaseAttribute("12.3", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("12.345", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("-100", "5", null)]
        public async global::System.Threading.Tasks.Task RP14ADisplayErrorForInvalidArrearsOfPayOwedFormat(string arrearsOfPay, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "allure.subSuite:Payment"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("arrearsOfPay", arrearsOfPay);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RP14A Display error for invalid arrears of pay owed format", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
        await this.FeatureBackgroundAsync();
#line hidden
#line 35
            await testRunner.GivenAsync(string.Format("the RP14A contains employee arrears of pay owed \"{0}\"", arrearsOfPay), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
             await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Message",
                            "Hint",
                            "Type"});
                table1.AddRow(new string[] {
                            "1 invalid arrears of pay owed",
                            "Expected format is 12.34 or 100",
                            "Employee arrears of payment owed"});
#line 37
             await testRunner.ThenAsync("I should see the following validation errors", ((string)(null)), table1, "Then ");
#line hidden
#line 40
              await testRunner.AndAsync("I should be able to view employee arrears of pay owed error details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("RP14A Display multiple errors for invalid arrears of pay owed format")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("allure.subSuite:Payment")]
        [global::NUnit.Framework.TestCaseAttribute("2", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("3", "7", null)]
        public async global::System.Threading.Tasks.Task RP14ADisplayMultipleErrorsForInvalidArrearsOfPayOwedFormat(string count, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "allure.subSuite:Payment"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("count", count);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RP14A Display multiple errors for invalid arrears of pay owed format", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 50
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
        await this.FeatureBackgroundAsync();
#line hidden
#line 51
            await testRunner.GivenAsync(string.Format("the RP14A contains {0} invalid arrears of pay owed", count), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 52
             await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Message",
                            "Hint",
                            "Type"});
                table2.AddRow(new string[] {
                            string.Format("{0} invalid arrears of pay owed", count),
                            "Expected format is 12.34 or 100",
                            "Employee arrears of payment owed"});
#line 53
             await testRunner.ThenAsync("I should see the following validation errors", ((string)(null)), table2, "Then ");
#line hidden
#line 56
              await testRunner.AndAsync("I should be able to view employee arrears of pay owed error details for multiple " +
                        "employees", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("RP14A Display error for missing employee national insurance number")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("allure.subSuite:NationalInsurance")]
        public async global::System.Threading.Tasks.Task RP14ADisplayErrorForMissingEmployeeNationalInsuranceNumber()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "allure.subSuite:NationalInsurance"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RP14A Display error for missing employee national insurance number", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 63
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
        await this.FeatureBackgroundAsync();
#line hidden
#line 64
            await testRunner.GivenAsync("the RP14A contains an employee with no national insurance number", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 65
             await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 66
             await testRunner.ThenAsync("I should see the national insurance number validation error \"[COUNT] missing the " +
                        "employee national insurance number\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 67
              await testRunner.AndAsync("I should be able to view national insurance number error details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("RP14A Display error for invalid employee national insurance number format")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("allure.subSuite:NationalInsurance")]
        [global::NUnit.Framework.TestCaseAttribute("123456789", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("AB12345C", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("QQ123456A", "11", null)]
        [global::NUnit.Framework.TestCaseAttribute("AB123456Z", "12", null)]
        public async global::System.Threading.Tasks.Task RP14ADisplayErrorForInvalidEmployeeNationalInsuranceNumberFormat(string nationalInsuranceNumber, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "allure.subSuite:NationalInsurance"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("nationalInsuranceNumber", nationalInsuranceNumber);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RP14A Display error for invalid employee national insurance number format", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 70
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
        await this.FeatureBackgroundAsync();
#line hidden
#line 71
            await testRunner.GivenAsync(string.Format("the RP14A contains employee national insurance number \"{0}\"", nationalInsuranceNumber), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 72
             await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
             await testRunner.ThenAsync("I should see the national insurance number validation error \"[COUNT] invalid empl" +
                        "oyee national insurance number format\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 74
              await testRunner.AndAsync("I should be able to view national insurance number error details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("RP14A Display error for invalid money owed to employer format")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("allure.subSuite:Payment")]
        [global::NUnit.Framework.TestCaseAttribute("12.3", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("12.345", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("-50", "15", null)]
        public async global::System.Threading.Tasks.Task RP14ADisplayErrorForInvalidMoneyOwedToEmployerFormat(string moneyOwed, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "allure.subSuite:Payment"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("moneyOwed", moneyOwed);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RP14A Display error for invalid money owed to employer format", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 83
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
        await this.FeatureBackgroundAsync();
#line hidden
#line 84
            await testRunner.GivenAsync(string.Format("the RP14A contains money owed to employer \"{0}\"", moneyOwed), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 85
             await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Message",
                            "Hint",
                            "Type"});
                table3.AddRow(new string[] {
                            "1 invalid money owed to employer",
                            "Expected format is 12.34 or 100",
                            "Money owed to employer"});
#line 86
             await testRunner.ThenAsync("I should see the following validation errors", ((string)(null)), table3, "Then ");
#line hidden
#line 89
              await testRunner.AndAsync("I should be able to view money owed to employer error details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("RP14A Display error when employment start date is after employment end date")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("allure.story:Employee")]
        public async global::System.Threading.Tasks.Task RP14ADisplayErrorWhenEmploymentStartDateIsAfterEmploymentEndDate()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "allure.story:Employee"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RP14A Display error when employment start date is after employment end date", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 99
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
        await this.FeatureBackgroundAsync();
#line hidden
#line 100
            await testRunner.GivenAsync("the RP14A contains employment start date \"2026-04-30\" with end date \"2026-04-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 101
             await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Message",
                            "Hint",
                            "Type"});
                table4.AddRow(new string[] {
                            "1 invalid employment dates for the employee",
                            "Start date must be before the end date",
                            "Employee employment dates"});
#line 102
             await testRunner.ThenAsync("I should see the following validation errors", ((string)(null)), table4, "Then ");
#line hidden
#line 105
              await testRunner.AndAsync("I should be able to view the employee employment dates error details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 106
              await testRunner.AndAsync("I should be able to go to the previous page from the error details page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("RP14A Display error when arrears of pay start date is after end date")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("allure.story:Payment")]
        public async global::System.Threading.Tasks.Task RP14ADisplayErrorWhenArrearsOfPayStartDateIsAfterEndDate()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "allure.story:Payment"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RP14A Display error when arrears of pay start date is after end date", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 110
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
        await this.FeatureBackgroundAsync();
#line hidden
#line 111
            await testRunner.GivenAsync("the RP14A contains arrears of pay start date \"2026-04-30\" and end date \"2026-04-0" +
                        "1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 112
             await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Message",
                            "Hint",
                            "Type"});
                table5.AddRow(new string[] {
                            "1 invalid arrears of dates",
                            "Start date must be before the end date",
                            "Employee arrears of payment dates"});
#line 113
             await testRunner.ThenAsync("I should see the following validation errors", ((string)(null)), table5, "Then ");
#line hidden
#line 116
              await testRunner.AndAsync("I should be able to view error details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Display error for invalid arrears of pay owed format")]
        [global::NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        public async global::System.Threading.Tasks.Task DisplayErrorForInvalidArrearsOfPayOwedFormat()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "ignore"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Display error for invalid arrears of pay owed format", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 119
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
        await this.FeatureBackgroundAsync();
#line hidden
#line 120
            await testRunner.GivenAsync("I am on the upload page as a \"Admin\" user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 121
              await testRunner.AndAsync("the RP14A contains employee arrears of pay owed \"abc\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 122
             await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 123
             await testRunner.ThenAsync("I should see the validation error \"1 invalid arrears of pay owed\" with the hint \"" +
                        "Expected format is 12.34 or 100\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 124
              await testRunner.AndAsync("I should be able to view employee arrears of pay owed error details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
