// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace GovUk.Forms.HostApp.UI.Test.Features.Validation
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Employer Validation")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("MEDS-1067")]
    public partial class EmployerValidationFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "MEDS-1067"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Validation", "Employer Validation", "              As an Insolvency Practitioner user\r\n              I want RP14A vali" +
                "dation to run before submission to Dynamics\r\n  So that I can fix errors immediat" +
                "ely and avoid delayed rejection", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "EmployerValidation.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
        #line hidden
#line 9
            await testRunner.GivenAsync("I am on the upload page as a \"Admin\" user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Validation/EmployerValidation.feature.ndjson", 9);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Employer name length boundary validation")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("addVideo")]
        [global::NUnit.Framework.TestCaseAttribute("99", "accepted", "none", "none", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("100", "rejected", "1 employer name is the wrong length", "Enter up to 99 characters", "1", null)]
        public async global::System.Threading.Tasks.Task EmployerNameLengthBoundaryValidation(string length, string outcome, string summaryBehaviour, string detailsBehaviour, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "addVideo"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("length", length);
            argumentsOfScenario.Add("outcome", outcome);
            argumentsOfScenario.Add("summaryBehaviour", summaryBehaviour);
            argumentsOfScenario.Add("detailsBehaviour", detailsBehaviour);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Employer name length boundary validation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
        await this.FeatureBackgroundAsync();
#line hidden
#line 13
            await testRunner.GivenAsync(string.Format("I have uploaded an RP14A file with employer name of length {0}", length), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
             await testRunner.WhenAsync("I submit the RP14A file", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
             await testRunner.ThenAsync(string.Format("the submission should be \"{0}\"", outcome), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
              await testRunner.AndAsync(string.Format("the error summary should \"{0}\" with \"{1}\"", summaryBehaviour, detailsBehaviour), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
              await testRunner.AndAsync("I should be able to view error details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("RP14A Display multiple validation categories together")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("addVideo")]
        public async global::System.Threading.Tasks.Task RP14ADisplayMultipleValidationCategoriesTogether()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "addVideo"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RP14A Display multiple validation categories together", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
        await this.FeatureBackgroundAsync();
#line hidden
#line 26
    await testRunner.GivenAsync("the RP14A contains multiple validation issues", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
    await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Category"});
                table1.AddRow(new string[] {
                            "Case"});
                table1.AddRow(new string[] {
                            "Employer"});
                table1.AddRow(new string[] {
                            "Employee"});
                table1.AddRow(new string[] {
                            "Employee pay"});
                table1.AddRow(new string[] {
                            "Employee holiday"});
#line 28
    await testRunner.ThenAsync("I should see the following validation categories", ((string)(null)), table1, "Then ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Category",
                            "Type",
                            "Message",
                            "Hint"});
                table2.AddRow(new string[] {
                            "Case",
                            "Case reference",
                            "1 case reference is missing",
                            "Enter a reference number like CN12345678"});
                table2.AddRow(new string[] {
                            "Employer",
                            "Employer name",
                            "1 employer name is the wrong length",
                            "Enter up to 99 characters"});
                table2.AddRow(new string[] {
                            "Employee",
                            "Employee surname",
                            "1 employee surname is missing",
                            ""});
                table2.AddRow(new string[] {
                            "Employee pay",
                            "Employee basic pay per week",
                            "1 weekly pay amount is incorrect",
                            "Enter a number like 12.34 or 100"});
                table2.AddRow(new string[] {
                            "Employee holiday",
                            "Holiday owed",
                            "1 holiday owed is incorrect",
                            "Enter a number like 28.25 or 33"});
                table2.AddRow(new string[] {
                            "Employee holiday",
                            "Holiday owed",
                            "1 holiday owed is outside the allowed range",
                            "Enter a value between 0 and 365"});
#line 35
    await testRunner.AndAsync("I should see the following multiple validation errors", ((string)(null)), table2, "And ");
#line hidden
#line 43
    await testRunner.AndAsync("I should be able to view error details for all validation categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("RP14A API display multiple validation categories together")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("addVideo")]
        [global::NUnit.Framework.CategoryAttribute("api-upload")]
        public async global::System.Threading.Tasks.Task RP14AAPIDisplayMultipleValidationCategoriesTogether()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "addVideo",
                    "api-upload"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RP14A API display multiple validation categories together", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 46
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
        await this.FeatureBackgroundAsync();
#line hidden
#line 47
    await testRunner.GivenAsync("the RP14A contains multiple validation issues", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 48
    await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Category"});
                table3.AddRow(new string[] {
                            "Case"});
                table3.AddRow(new string[] {
                            "Employer"});
                table3.AddRow(new string[] {
                            "Employee"});
                table3.AddRow(new string[] {
                            "Employee pay"});
                table3.AddRow(new string[] {
                            "Employee holiday"});
#line 49
    await testRunner.ThenAsync("I should see the following validation categories", ((string)(null)), table3, "Then ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Category",
                            "Type",
                            "Message",
                            "Hint"});
                table4.AddRow(new string[] {
                            "Case",
                            "Case reference",
                            "1 case reference is missing",
                            "Enter a reference number like CN12345678"});
                table4.AddRow(new string[] {
                            "Employee",
                            "Employee surname",
                            "1 employee surname is missing",
                            ""});
                table4.AddRow(new string[] {
                            "Employee pay",
                            "Employee basic pay per week",
                            "1 weekly pay amount is incorrect",
                            "Enter a number like 12.34 or 100"});
                table4.AddRow(new string[] {
                            "Employee holiday",
                            "Holiday owed",
                            "1 holiday owed is incorrect",
                            "Enter a number like 28.25 or 33"});
                table4.AddRow(new string[] {
                            "Employee holiday",
                            "Holiday owed",
                            "1 holiday owed is outside the allowed range",
                            "Enter a value between 0 and 365"});
#line 56
    await testRunner.AndAsync("I should see the following multiple validation errors", ((string)(null)), table4, "And ");
#line hidden
#line 63
    await testRunner.AndAsync("I should be able to view error details for all validation categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Multiple employer names exceeding allowed length are rejected")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("addVideo")]
        public async global::System.Threading.Tasks.Task MultipleEmployerNamesExceedingAllowedLengthAreRejected()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "addVideo"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Multiple employer names exceeding allowed length are rejected", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 67
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
        await this.FeatureBackgroundAsync();
#line hidden
#line 68
         await testRunner.GivenAsync("I have uploaded an RP14A file with 3 employer names of length 100", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 69
         await testRunner.WhenAsync("I submit the RP14A file", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 70
         await testRunner.ThenAsync("the submission should be \"rejected\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 71
          await testRunner.AndAsync("the error summary should \"3 employer names are the wrong length\" with \"Enter up t" +
                        "o 99 characters\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
          await testRunner.AndAsync("I should be able to view error details for multiple employees", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("RP14A Display multiple errors for the same employee")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("addVideo")]
        public async global::System.Threading.Tasks.Task RP14ADisplayMultipleErrorsForTheSameEmployee()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "addVideo"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RP14A Display multiple errors for the same employee", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 75
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
        await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Surname",
                            "NationalInsuranceNumber",
                            "MoneyOwedToEmployer",
                            "BasicPayPerWeek"});
                table5.AddRow(new string[] {
                            "",
                            "QQ123456A",
                            "12.345",
                            "12.3"});
#line 76
            await testRunner.GivenAsync("the RP14A contains an employee with:", ((string)(null)), table5, "Given ");
#line hidden
#line 79
             await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Category",
                            "Type",
                            "Message",
                            "Hint"});
                table6.AddRow(new string[] {
                            "Employee",
                            "Employee surname",
                            "1 employee surname is missing",
                            ""});
                table6.AddRow(new string[] {
                            "Employee",
                            "Employee national insurance number",
                            "1 National Insurance number is in the wrong format",
                            "Enter a National Insurance number like QQ 12 34 56 C"});
                table6.AddRow(new string[] {
                            "Employee",
                            "Money owed to employer",
                            "1 amount owed to the employer is incorrect",
                            "Enter a number like 12.34 or 100"});
                table6.AddRow(new string[] {
                            "Employee pay",
                            "Employee basic pay per week",
                            "1 weekly pay amount is incorrect",
                            "Enter a number like 12.34 or 100"});
#line 80
             await testRunner.ThenAsync("I should see the following multiple validation errors", ((string)(null)), table6, "Then ");
#line hidden
#line 86
             await testRunner.AndAsync("I should be able to view error details for all validation categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("RP14A API display multiple errors for the same employee")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("addVideo")]
        [global::NUnit.Framework.CategoryAttribute("api-upload")]
        public async global::System.Threading.Tasks.Task RP14AAPIDisplayMultipleErrorsForTheSameEmployee()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "addVideo",
                    "api-upload"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RP14A API display multiple errors for the same employee", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 89
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
        await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Surname",
                            "NationalInsuranceNumber",
                            "MoneyOwedToEmployer",
                            "BasicPayPerWeek"});
                table7.AddRow(new string[] {
                            "",
                            "QQ123456A",
                            "12.345",
                            "12.3"});
#line 90
            await testRunner.GivenAsync("the RP14A contains an employee with:", ((string)(null)), table7, "Given ");
#line hidden
#line 93
             await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Category",
                            "Type",
                            "Message",
                            "Hint"});
                table8.AddRow(new string[] {
                            "Employee",
                            "Employee surname",
                            "1 employee surname is missing",
                            ""});
                table8.AddRow(new string[] {
                            "Employee",
                            "Employee national insurance number",
                            "1 National Insurance number is in the wrong format",
                            "Enter a National Insurance number like QQ 12 34 56 C"});
                table8.AddRow(new string[] {
                            "Employee",
                            "Money owed to employer",
                            "1 amount owed to the employer is incorrect",
                            "Enter a number like 12.34 or 100"});
                table8.AddRow(new string[] {
                            "Employee pay",
                            "Employee basic pay per week",
                            "1 weekly pay amount is incorrect",
                            "Enter a number like 12.34 or 100"});
#line 94
             await testRunner.ThenAsync("I should see the following multiple validation errors", ((string)(null)), table8, "Then ");
#line hidden
#line 100
             await testRunner.AndAsync("I should be able to view error details for all validation categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
