// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace GovUk.Forms.HostApp.UI.Test.Features.Validation
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Employer Validation")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("MEDS-1067")]
    public partial class EmployerValidationFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "MEDS-1067"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Validation", "Employer Validation", "              As an Insolvency Practitioner user\r\n              I want RP14A vali" +
                "dation to run before submission to Dynamics\r\n  So that I can fix errors immediat" +
                "ely and avoid delayed rejection", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "EmployerValidation.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
        #line hidden
#line 9
            await testRunner.GivenAsync("I am on the upload page as a \"Admin\" user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Validation/EmployerValidation.feature.ndjson", 5);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Employer name length boundary validation")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.TestCaseAttribute("99", "accepted", "none", "none", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("100", "rejected", "1 invalid length of the employer name", "Maximum of 99 characters allowed", "1", null)]
        public async global::System.Threading.Tasks.Task EmployerNameLengthBoundaryValidation(string length, string outcome, string summaryBehaviour, string detailsBehaviour, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "regression",
                    "validation",
                    "rp14a"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("length", length);
            argumentsOfScenario.Add("outcome", outcome);
            argumentsOfScenario.Add("summaryBehaviour", summaryBehaviour);
            argumentsOfScenario.Add("detailsBehaviour", detailsBehaviour);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Employer name length boundary validation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
        this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
        await this.FeatureBackgroundAsync();
#line hidden
#line 13
            await testRunner.GivenAsync(string.Format("I have uploaded an RP14A file with employer name of length {0}", length), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
             await testRunner.WhenAsync("I submit the RP14A file", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
             await testRunner.ThenAsync(string.Format("the submission should be \"{0}\"", outcome), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
              await testRunner.AndAsync(string.Format("the error summary should \"{0}\" with \"{1}\"", summaryBehaviour, detailsBehaviour), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
              await testRunner.AndAsync("I should be able to view error details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("RP14A Display multiple validation categories together")]
        [global::NUnit.Framework.CategoryAttribute("regression")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("rp14a")]
        [global::NUnit.Framework.CategoryAttribute("addScreencast")]
        public async global::System.Threading.Tasks.Task RP14ADisplayMultipleValidationCategoriesTogether()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "validation",
                    "rp14a",
                    "addScreencast"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RP14A Display multiple validation categories together", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
        await this.FeatureBackgroundAsync();
#line hidden
#line 26
    await testRunner.GivenAsync("the RP14A contains multiple validation issues", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
    await testRunner.WhenAsync("I attempt to submit the RP14A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "Category"});
                table18.AddRow(new string[] {
                            "Case"});
                table18.AddRow(new string[] {
                            "Employer"});
                table18.AddRow(new string[] {
                            "Employee"});
                table18.AddRow(new string[] {
                            "Employee pay"});
                table18.AddRow(new string[] {
                            "Employee holiday"});
#line 28
    await testRunner.ThenAsync("I should see the following validation categories", ((string)(null)), table18, "Then ");
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "Category",
                            "Type",
                            "Message",
                            "Hint"});
                table19.AddRow(new string[] {
                            "Case",
                            "Case reference",
                            "1 missing a case reference",
                            ""});
                table19.AddRow(new string[] {
                            "Case",
                            "Case reference",
                            "1 invalid case reference format",
                            "Format is CN12345678"});
                table19.AddRow(new string[] {
                            "Employer",
                            "Employer name",
                            "1 invalid length of the employer name",
                            "Maximum of 99 characters allowed"});
                table19.AddRow(new string[] {
                            "Employee",
                            "Employee surname",
                            "1 missing employee surname",
                            ""});
                table19.AddRow(new string[] {
                            "Employee pay",
                            "Employee basic pay per week",
                            "1 invalid basic pay per week",
                            "Expected format is 12.34 or 100"});
                table19.AddRow(new string[] {
                            "Employee holiday",
                            "Holiday owed",
                            "1 invalid holiday owed",
                            "Expected format is 28.25 or 33"});
                table19.AddRow(new string[] {
                            "Employee holiday",
                            "Holiday owed",
                            "1 invalid range of holiday owed",
                            "0 to 365 days allowed"});
#line 35
    await testRunner.AndAsync("I should see the following multiple validation errors", ((string)(null)), table19, "And ");
#line hidden
#line 44
    await testRunner.AndAsync("I should be able to view error details for all validation categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
