using System.Text.RegularExpressions;
using GovUk.Forms.Application.Clients;
using GovUk.Forms.Domain.Search;

namespace Inss.GovUk.Forms.Iir.Infrastructure.Clients;

public sealed class MockSearchClient : ISearchClient
{
    private static readonly SearchResult[] _searchResultList = CreateMockSearchResults();
    
    public Task<SearchResponse> SearchAsync(SearchRequest request)
    {
        SearchResult[] searchedResults = _searchResultList
            .Where(r => Regex.IsMatch(r.Fields["GlobalSearchField"], request.SearchText, RegexOptions.IgnoreCase) ||
                        Regex.IsMatch(r.Fields["TradeNamesSearchField"], request.SearchText, RegexOptions.IgnoreCase) ||
                        Regex.IsMatch(r.Fields["LastNamesSearchField"], request.SearchText, RegexOptions.IgnoreCase) ||
                        Regex.IsMatch(r.Fields["ForeNamesSearchField"], request.SearchText, RegexOptions.IgnoreCase))
            .ToArray();
        
        return Task.FromResult(new SearchResponse
        {
            TotalResults = searchedResults.Length,
            Results = searchedResults.Skip(request.Skip).Take(request.PageSize).ToArray()
        });
    }

    public Task<SearchDetailResponse?> SearchDetailAsync(SearchDetailRequest request)
    {
        SearchResult? result = _searchResultList.FirstOrDefault(r => r.Fields[request.KeyField] == request.KeyValue);

        return Task.FromResult(
            result is not null 
                ? new SearchDetailResponse { Result = new SearchResult { Fields = result.Fields } }
                : null);
    }

    private static SearchResult[] CreateMockSearchResults()
    {
        List<SearchResult> searchResults = [];
        Dictionary<string, string> fields = [];

        fields.Add("Case_Indiv_No", "704406359_709885771");
        fields.Add("CaseNumber", "704406359");
        fields.Add("IndividualNumber", "709885771");
        fields.Add("GlobalSearchField", "704406359 709885771 Sherborne St. John RG24 9LA");
        fields.Add("TradeNamesSearchField", "Scott Chapman Property Maintenance");
        fields.Add("LastNamesSearchField", "CHAPMAN");
        fields.Add("ForeNamesSearchField", "SCOTT JOHN");
        fields.Add("FirstName", "SCOTT JOHN");
        fields.Add("FamilyName", "CHAPMAN");
        fields.Add("Title", "Mr");
        fields.Add("AlternativeNames", "No OtherNames Found");
        fields.Add("Gender", "Male");
        fields.Add("Occupation", "Skilled trades");
        fields.Add("LastKnownTown", "Sherborne St. John");
        fields.Add("LastKnownAddress", "Prospect House, 1 Aldermaston Road, Sherborne St. John, Basingstoke, United Kingdom");
        fields.Add("LastKnownPostcode", "RG24 9LA");
        fields.Add("AddressWithheld", "N");
        fields.Add("DateOfBirth", "02/04/1990");
        fields.Add("CaseName", "Scott John Chapman");
        fields.Add("Court", "Office of the Adjudicator");
        fields.Add("CourtNumber", "5158202");
        fields.Add("CaseYear", "2024");
        fields.Add("InsolvencyType", "Bankruptcy");
        fields.Add("InsolvencyDate", "06/03/2024");
        fields.Add("NotificationDate", "0001-01-01T00:00:00Z");
        fields.Add("CaseStatus", "Currently Bankrupt : Automatic Discharge will be 06/03/2025");
        fields.Add("CaseDescription", "Scott John Chapman, Self Employed, of Prospect House, 1 Aldermaston Road, Sherborne St. John, Basingstoke, Hampshire, RG24 9LA, formerly of 106 Packenham Road, Basingstoke, Hampshire, RG21 8XX and carrying on business as Scott Chapman Property Maintenance");
        fields.Add("TradingData", "<Trading><TradingDetails><TradingName>Scott Chapman Property Maintenance</TradingName><TradingAddress>1 Aldermaston Road, Sherborne St. John, BASINGSTOKE, United Kingdom, RG24 9LA</TradingAddress></TradingDetails></Trading>");
        fields.Add("TradingNames", "Scott Chapman Property Maintenance");
        fields.Add("OtherForenames", "[]");
        fields.Add("OtherSurnames", "[]");
        fields.Add("HasRestrictions", "false");
        fields.Add("RestrictionsType", "");
        fields.Add("RestrictionsStartDate", "");
        fields.Add("RestrictionsEndDate", "");
        fields.Add("HasPrevInterimRestrictionsOrder", "false");
        fields.Add("PrevInterimRestrictionsOrderStartDate", "");
        fields.Add("PrevInterimRestrictionsOrderEndDate", "");
        fields.Add("PractitionerName", "");
        fields.Add("PractitionerFirmName", "");
        fields.Add("PractitionerAddress", "");
        fields.Add("PractitionerPostcode", "");
        fields.Add("PractitionerTelephone", "");
        fields.Add("InsolvencyServiceOffice", "OR Central Case Team");
        fields.Add("InsolvencyServiceContact", "Enquiry Desk");
        fields.Add("InsolvencyServiceAddress", "PO Box 18416, Birmingham, United Kingdom");
        fields.Add("InsolvencyServicePostcode", "B2 2UB");
        fields.Add("InsolvencyServiceTelephone", "0300 6780 016");
        fields.Add("DateOfPreviousOrder", "");
        fields.Add("DeceasedDate", "");
        SearchResult searchResult = new() { Fields = fields };
        searchResults.Add(searchResult);

        fields = [];
        fields.Add("Case_Indiv_No", "703223843_707433163");
        fields.Add("CaseNumber", "703223843");
        fields.Add("IndividualNumber", "707433163");
        fields.Add("GlobalSearchField", "703223843 707433163 TR11 4SR");
        fields.Add("TradeNamesSearchField", "");
        fields.Add("LastNamesSearchField", "AMY");
        fields.Add("ForeNamesSearchField", "ROBERT JOHN");
        fields.Add("FirstName", "ROBERT JOHN");
        fields.Add("FamilyName", "AMY");
        fields.Add("Title", "Mr");
        fields.Add("AlternativeNames", "No OtherNames Found");
        fields.Add("Gender", "Male");
        fields.Add("Occupation", "No Occupation Found");
        fields.Add("LastKnownTown", "");
        fields.Add("LastKnownAddress", "116 Longfield, Falmouth, GBR");
        fields.Add("LastKnownPostcode", "TR11 4SR");
        fields.Add("AddressWithheld", "N");
        fields.Add("DateOfBirth", "13/03/1994");
        fields.Add("CaseName", "Robert John Amy");
        fields.Add("Court", "Voluntary Liquidation Cases");
        fields.Add("CourtNumber", "");
        fields.Add("CaseYear", "(Case Year does not apply to IVA)");
        fields.Add("InsolvencyType", "Individual Voluntary Arrangement");
        fields.Add("InsolvencyDate", "12/12/2019");
        fields.Add("NotificationDate", "2020-05-14T00:00:00Z");
        fields.Add("CaseStatus", "Current");
        fields.Add("CaseDescription", "(Case Description does not apply to IVA)");
        fields.Add("TradingData", "<No Trading Names Found>");
        fields.Add("TradingNames", "");
        fields.Add("OtherForenames", "[]");
        fields.Add("OtherSurnames", "[]");
        fields.Add("HasRestrictions", "false");
        fields.Add("RestrictionsType", "");
        fields.Add("RestrictionsStartDate", "");
        fields.Add("RestrictionsEndDate", "");
        fields.Add("HasPrevInterimRestrictionsOrder", "false");
        fields.Add("PrevInterimRestrictionsOrderStartDate", "");
        fields.Add("PrevInterimRestrictionsOrderEndDate", "");
        fields.Add("PractitionerName", "Lucy Griffin");
        fields.Add("PractitionerFirmName", "Creditfix Ltd");
        fields.Add("PractitionerAddress", "3rd Floor, 4 West Regent Street, Glasgow, United Kingdom");
        fields.Add("PractitionerPostcode", "G2 1RW");
        fields.Add("PractitionerTelephone", "0141 565 1300");
        fields.Add("InsolvencyServiceOffice", "The Insolvency Service");
        fields.Add("InsolvencyServiceContact", "Enquiry Desk");
        fields.Add("InsolvencyServiceAddress", "Cannon House, 18 Priory Queensway, Birmingham, United Kingdom");
        fields.Add("InsolvencyServicePostcode", "B4 6FD");
        fields.Add("InsolvencyServiceTelephone", "0303 003 1742");
        fields.Add("DateOfPreviousOrder", "");
        fields.Add("DeceasedDate", "");
        searchResult = new() { Fields = fields };
        searchResults.Add(searchResult);

        fields = [];
        fields.Add("Case_Indiv_No", "702227091_704948341");
        fields.Add("CaseNumber", "702227091");
        fields.Add("IndividualNumber", "704948341");
        fields.Add("GlobalSearchField", "702227091 704948341 CF32 9BA");
        fields.Add("TradeNamesSearchField", "");
        fields.Add("LastNamesSearchField", "DEE");
        fields.Add("ForeNamesSearchField", "MALCOLM JOHN");
        fields.Add("FirstName", "MALCOLM JOHN");
        fields.Add("FamilyName", "DEE");
        fields.Add("Title", "Mr");
        fields.Add("AlternativeNames", "No OtherNames Found");
        fields.Add("Gender", "Male");
        fields.Add("Occupation", "No Occupation Found");
        fields.Add("LastKnownTown", "");
        fields.Add("LastKnownAddress", "58B Bridgend Road, Aberkenfig, GBR");
        fields.Add("LastKnownPostcode", "CF32 9BA");
        fields.Add("AddressWithheld", "N");
        fields.Add("DateOfBirth", "31/08/1956");
        fields.Add("CaseName", "Malcolm John Dee");
        fields.Add("Court", "Voluntary Liquidation Cases");
        fields.Add("CourtNumber", "");
        fields.Add("CaseYear", "(Case Year does not apply to IVA)");
        fields.Add("InsolvencyType", "Individual Voluntary Arrangement");
        fields.Add("InsolvencyDate", "13/04/2017");
        fields.Add("NotificationDate", "2017-04-24T00:00:00Z");
        fields.Add("CaseStatus", "Current");
        fields.Add("CaseDescription", "(Case Description does not apply to IVA)");
        fields.Add("TradingData", "<No Trading Names Found>");
        fields.Add("TradingNames", "");
        fields.Add("OtherForenames", "[]");
        fields.Add("OtherSurnames", "[]");
        fields.Add("HasRestrictions", "false");
        fields.Add("RestrictionsType", "");
        fields.Add("RestrictionsStartDate", "");
        fields.Add("RestrictionsEndDate", "");
        fields.Add("HasPrevInterimRestrictionsOrder", "false");
        fields.Add("PrevInterimRestrictionsOrderStartDate", "");
        fields.Add("PrevInterimRestrictionsOrderEndDate", "");
        fields.Add("PractitionerName", "KATY WALKER");
        fields.Add("PractitionerFirmName", "CREDITFIX LIMITED");
        fields.Add("PractitionerAddress", "3rd floor, 4 West Regent Street, GLASGOW, United Kingdom");
        fields.Add("PractitionerPostcode", "G2 1RW");
        fields.Add("PractitionerTelephone", "0800 043 1431");
        fields.Add("InsolvencyServiceOffice", "The Insolvency Service");
        fields.Add("InsolvencyServiceContact", "Enquiry Desk");
        fields.Add("InsolvencyServiceAddress", "Cannon House, 18 Priory Queensway, Birmingham, United Kingdom");
        fields.Add("InsolvencyServicePostcode", "B4 6FD");
        fields.Add("InsolvencyServiceTelephone", "0303 003 1742");
        fields.Add("DateOfPreviousOrder", "");
        fields.Add("DeceasedDate", "");
        searchResult = new() { Fields = fields };
        searchResults.Add(searchResult);

        fields = [];
        fields.Add("Case_Indiv_No", "703537953_708106455");
        fields.Add("CaseNumber", "703537953");
        fields.Add("IndividualNumber", "708106455");
        fields.Add("GlobalSearchField", "703537953 708106455 TF6 6BN");
        fields.Add("TradeNamesSearchField", "");
        fields.Add("LastNamesSearchField", "HOLDER");
        fields.Add("ForeNamesSearchField", "KY");
        fields.Add("FirstName", "KY");
        fields.Add("FamilyName", "HOLDER");
        fields.Add("Title", "Mr");
        fields.Add("AlternativeNames", "No OtherNames Found");
        fields.Add("Gender", "Male");
        fields.Add("Occupation", "No Occupation Found");
        fields.Add("LastKnownTown", "");
        fields.Add("LastKnownAddress", "8 Marlbrook Way, Telford, GBR");
        fields.Add("LastKnownPostcode", "TF6 6BN");
        fields.Add("AddressWithheld", "N");
        fields.Add("DateOfBirth", "04/03/1991");
        fields.Add("CaseName", "Ky Holder");
        fields.Add("Court", "Voluntary Liquidation Cases");
        fields.Add("CourtNumber", "");
        fields.Add("CaseYear", "(Case Year does not apply to IVA)");
        fields.Add("InsolvencyType", "Individual Voluntary Arrangement");
        fields.Add("InsolvencyDate", "12/04/2021");
        fields.Add("NotificationDate", "2021-06-11T00:00:00Z");
        fields.Add("CaseStatus", "Current");
        fields.Add("CaseDescription", "(Case Description does not apply to IVA)");
        fields.Add("TradingData", "<No Trading Names Found>");
        fields.Add("TradingNames", "");
        fields.Add("OtherForenames", "[]");
        fields.Add("OtherSurnames", "[]");
        fields.Add("HasRestrictions", "false");
        fields.Add("RestrictionsType", "");
        fields.Add("RestrictionsStartDate", "");
        fields.Add("RestrictionsEndDate", "");
        fields.Add("HasPrevInterimRestrictionsOrder", "false");
        fields.Add("PrevInterimRestrictionsOrderStartDate", "");
        fields.Add("PrevInterimRestrictionsOrderEndDate", "");
        fields.Add("PractitionerName", "Tracey Howarth");
        fields.Add("PractitionerFirmName", "The Insolvency Group");
        fields.Add("PractitionerAddress", "Crescent House, Lever Street, BOLTON, United Kingdom");
        fields.Add("PractitionerPostcode", "BL3 6NN");
        fields.Add("PractitionerTelephone", "0161 543 2310");
        fields.Add("InsolvencyServiceOffice", "The Insolvency Service");
        fields.Add("InsolvencyServiceContact", "Enquiry Desk");
        fields.Add("InsolvencyServiceAddress", "Cannon House, 18 Priory Queensway, Birmingham, United Kingdom");
        fields.Add("InsolvencyServicePostcode", "B4 6FD");
        fields.Add("InsolvencyServiceTelephone", "0303 003 1742");
        fields.Add("DateOfPreviousOrder", "");
        fields.Add("DeceasedDate", "");
        searchResult = new() { Fields = fields };
        searchResults.Add(searchResult);

        fields = [];
        fields.Add("Case_Indiv_No", "702268767_705053697");
        fields.Add("CaseNumber", "702268767");
        fields.Add("IndividualNumber", "705053697");
        fields.Add("GlobalSearchField", "702268767 705053697 CW5 5JT");
        fields.Add("TradeNamesSearchField", "");
        fields.Add("LastNamesSearchField", "NASH");
        fields.Add("ForeNamesSearchField", "SARAH");
        fields.Add("FirstName", "SARAH");
        fields.Add("FamilyName", "NASH");
        fields.Add("Title", "Miss");
        fields.Add("AlternativeNames", "No OtherNames Found");
        fields.Add("Gender", "Female");
        fields.Add("Occupation", "No Occupation Found");
        fields.Add("LastKnownTown", "");
        fields.Add("LastKnownAddress", "37 Gerard Drive, Nantwich, GBR");
        fields.Add("LastKnownPostcode", "CW5 5JT");
        fields.Add("AddressWithheld", "N");
        fields.Add("DateOfBirth", "21/08/1990");
        fields.Add("CaseName", "Sarah Nash");
        fields.Add("Court", "Voluntary Liquidation Cases");
        fields.Add("CourtNumber", "");
        fields.Add("CaseYear", "(Case Year does not apply to IVA)");
        fields.Add("InsolvencyType", "Individual Voluntary Arrangement");
        fields.Add("InsolvencyDate", "24/04/2017");
        fields.Add("NotificationDate", "2017-06-15T00:00:00Z");
        fields.Add("CaseStatus", "Current");
        fields.Add("CaseDescription", "(Case Description does not apply to IVA)");
        fields.Add("TradingData", "<No Trading Names Found>");
        fields.Add("TradingNames", "");
        fields.Add("OtherForenames", "[]");
        fields.Add("OtherSurnames", "[]");
        fields.Add("HasRestrictions", "false");
        fields.Add("RestrictionsType", "");
        fields.Add("RestrictionsStartDate", "");
        fields.Add("RestrictionsEndDate", "");
        fields.Add("HasPrevInterimRestrictionsOrder", "false");
        fields.Add("PrevInterimRestrictionsOrderStartDate", "");
        fields.Add("PrevInterimRestrictionsOrderEndDate", "");
        fields.Add("PractitionerName", "TIMOTHY JAMES POPE");
        fields.Add("PractitionerFirmName", "CREDITFIX LIMITED");
        fields.Add("PractitionerAddress", "3rd floor, 4 West Regent Street, GLASGOW, United Kingdom");
        fields.Add("PractitionerPostcode", "G2 1RW");
        fields.Add("PractitionerTelephone", "0800 043 1431");
        fields.Add("InsolvencyServiceOffice", "The Insolvency Service");
        fields.Add("InsolvencyServiceContact", "Enquiry Desk");
        fields.Add("InsolvencyServiceAddress", "Cannon House, 18 Priory Queensway, Birmingham, United Kingdom");
        fields.Add("InsolvencyServicePostcode", "B4 6FD");
        fields.Add("InsolvencyServiceTelephone", "0303 003 1742");
        fields.Add("DateOfPreviousOrder", "");
        fields.Add("DeceasedDate", "");
        searchResult = new() { Fields = fields };
        searchResults.Add(searchResult);

        fields = [];
        fields.Add("Case_Indiv_No", "702522995_705668923");
        fields.Add("CaseNumber", "702522995");
        fields.Add("IndividualNumber", "705668923");
        fields.Add("GlobalSearchField", "702522995 705668923 SS17 7SE");
        fields.Add("TradeNamesSearchField", "");
        fields.Add("LastNamesSearchField", "BEER");
        fields.Add("ForeNamesSearchField", "SARAH");
        fields.Add("FirstName", "SARAH");
        fields.Add("FamilyName", "BEER");
        fields.Add("Title", "Mrs");
        fields.Add("AlternativeNames", "No OtherNames Found");
        fields.Add("Gender", "Female");
        fields.Add("Occupation", "No Occupation Found");
        fields.Add("LastKnownTown", "");
        fields.Add("LastKnownAddress", "6 Gardner Avenue, Stanford-Le-Hope, GBR");
        fields.Add("LastKnownPostcode", "SS17 7SE");
        fields.Add("AddressWithheld", "N");
        fields.Add("DateOfBirth", "27/04/1985");
        fields.Add("CaseName", "Sarah Beer");
        fields.Add("Court", "Voluntary Liquidation Cases");
        fields.Add("CourtNumber", "");
        fields.Add("CaseYear", "(Case Year does not apply to IVA)");
        fields.Add("InsolvencyType", "Individual Voluntary Arrangement");
        fields.Add("InsolvencyDate", "28/03/2018");
        fields.Add("NotificationDate", "2018-04-10T00:00:00Z");
        fields.Add("CaseStatus", "Current");
        fields.Add("CaseDescription", "(Case Description does not apply to IVA)");
        fields.Add("TradingData", "<No Trading Names Found>");
        fields.Add("TradingNames", "");
        fields.Add("OtherForenames", "[]");
        fields.Add("OtherSurnames", "[]");
        fields.Add("HasRestrictions", "false");
        fields.Add("RestrictionsType", "");
        fields.Add("RestrictionsStartDate", "");
        fields.Add("RestrictionsEndDate", "");
        fields.Add("HasPrevInterimRestrictionsOrder", "false");
        fields.Add("PrevInterimRestrictionsOrderStartDate", "");
        fields.Add("PrevInterimRestrictionsOrderEndDate", "");
        fields.Add("PractitionerName", "DAVID RANKIN");
        fields.Add("PractitionerFirmName", "CREDITFIX LIMITED");
        fields.Add("PractitionerAddress", "Floor 3, 4 West Regent Street, GLASGOW, United Kingdom");
        fields.Add("PractitionerPostcode", "G2 1RW");
        fields.Add("PractitionerTelephone", "");
        fields.Add("InsolvencyServiceOffice", "The Insolvency Service");
        fields.Add("InsolvencyServiceContact", "Enquiry Desk");
        fields.Add("InsolvencyServiceAddress", "Cannon House, 18 Priory Queensway, Birmingham, United Kingdom");
        fields.Add("InsolvencyServicePostcode", "B4 6FD");
        fields.Add("InsolvencyServiceTelephone", "0303 003 1742");
        fields.Add("DateOfPreviousOrder", "");
        fields.Add("DeceasedDate", "");
        searchResult = new() { Fields = fields };
        searchResults.Add(searchResult);

        fields = [];
        fields.Add("Case_Indiv_No", "703903137_708827259");
        fields.Add("CaseNumber", "703903137");
        fields.Add("IndividualNumber", "708827259");
        fields.Add("GlobalSearchField", "703903137 708827259 CA11 8LL");
        fields.Add("TradeNamesSearchField", "");
        fields.Add("LastNamesSearchField", "PATTINSON-GRAHAM Graham");
        fields.Add("ForeNamesSearchField", "TAN");
        fields.Add("FirstName", "TAN");
        fields.Add("FamilyName", "PATTINSON-GRAHAM");
        fields.Add("Title", "Miss");
        fields.Add("AlternativeNames", "<OtherNames><OtherName><Forenames></Forenames><Surname>Graham</Surname></OtherName></OtherNames>");
        fields.Add("Gender", "Female");
        fields.Add("Occupation", "No Occupation Found");
        fields.Add("LastKnownTown", "");
        fields.Add("LastKnownAddress", "25 Sim Court, Penrith, GBR");
        fields.Add("LastKnownPostcode", "CA11 8LL");
        fields.Add("AddressWithheld", "N");
        fields.Add("DateOfBirth", "02/04/1979");
        fields.Add("CaseName", "Tan Pattinson-Graham");
        fields.Add("Court", "Voluntary Liquidation Cases");
        fields.Add("CourtNumber", "");
        fields.Add("CaseYear", "(Case Year does not apply to IVA)");
        fields.Add("InsolvencyType", "Individual Voluntary Arrangement");
        fields.Add("InsolvencyDate", "27/07/2022");
        fields.Add("NotificationDate", "2022-08-08T00:00:00Z");
        fields.Add("CaseStatus", "Current");
        fields.Add("CaseDescription", "(Case Description does not apply to IVA)");
        fields.Add("TradingData", "<No Trading Names Found>");
        fields.Add("TradingNames", "");
        fields.Add("OtherForenames", "[]");
        fields.Add("OtherSurnames", "[\"Graham\"]");
        fields.Add("HasRestrictions", "false");
        fields.Add("RestrictionsType", "");
        fields.Add("RestrictionsStartDate", "");
        fields.Add("RestrictionsEndDate", "");
        fields.Add("HasPrevInterimRestrictionsOrder", "false");
        fields.Add("PrevInterimRestrictionsOrderStartDate", "");
        fields.Add("PrevInterimRestrictionsOrderEndDate", "");
        fields.Add("PractitionerName", "Tracy Whittaker");
        fields.Add("PractitionerFirmName", "Creditfix Ltd");
        fields.Add("PractitionerAddress", "3rd Floor, 4 West Regent Street, Glasgow, United Kingdom");
        fields.Add("PractitionerPostcode", "G2 1RW");
        fields.Add("PractitionerTelephone", "0141 565 1300");
        fields.Add("InsolvencyServiceOffice", "The Insolvency Service");
        fields.Add("InsolvencyServiceContact", "Enquiry Desk");
        fields.Add("InsolvencyServiceAddress", "Cannon House, 18 Priory Queensway, Birmingham, United Kingdom");
        fields.Add("InsolvencyServicePostcode", "B4 6FD");
        fields.Add("InsolvencyServiceTelephone", "0303 003 1742");
        fields.Add("DateOfPreviousOrder", "");
        fields.Add("DeceasedDate", "");
        searchResult = new() { Fields = fields };
        searchResults.Add(searchResult);

        fields = [];
        fields.Add("Case_Indiv_No", "42277465_1");
        fields.Add("CaseNumber", "42277465");
        fields.Add("IndividualNumber", "1");
        fields.Add("GlobalSearchField", "42277465 1 E2 6AH");
        fields.Add("TradeNamesSearchField", "");
        fields.Add("LastNamesSearchField", "KHAN");
        fields.Add("ForeNamesSearchField", "KAM");
        fields.Add("FirstName", "KAM");
        fields.Add("FamilyName", "KHAN");
        fields.Add("Title", "Mr");
        fields.Add("AlternativeNames", "No OtherNames Found");
        fields.Add("Gender", "Male");
        fields.Add("Occupation", "Unknown");
        fields.Add("LastKnownTown", "");
        fields.Add("LastKnownAddress", "287 Bethnal Green Road, London");
        fields.Add("LastKnownPostcode", "E2 6AH");
        fields.Add("AddressWithheld", "N");
        fields.Add("DateOfBirth", "No Date of Birth Found");
        fields.Add("CaseName", "KAM KHAN");
        fields.Add("Court", "High Court Of Justice");
        fields.Add("CourtNumber", "0010792");
        fields.Add("CaseYear", "2007");
        fields.Add("InsolvencyType", "Bankruptcy");
        fields.Add("InsolvencyDate", "12/02/2008");
        fields.Add("NotificationDate", "0001-01-01T00:00:00Z");
        fields.Add("CaseStatus", "Discharge Suspended Indefinitely (from 23/05/2008)");
        fields.Add("CaseDescription", "KAM KHAN OCCUPATION UNKNOWN OF AND TRADING AT 287 BETHNALGREEN ROAD LONDON   E2 6AH AS AN UNKNOWN OCCUPATION");
        fields.Add("TradingData", "<No Trading Names Found>");
        fields.Add("TradingNames", "");
        fields.Add("OtherForenames", "[]");
        fields.Add("OtherSurnames", "[]");
        fields.Add("HasRestrictions", "false");
        fields.Add("RestrictionsType", "");
        fields.Add("RestrictionsStartDate", "");
        fields.Add("RestrictionsEndDate", "");
        fields.Add("HasPrevInterimRestrictionsOrder", "false");
        fields.Add("PrevInterimRestrictionsOrderStartDate", "");
        fields.Add("PrevInterimRestrictionsOrderEndDate", "");
        fields.Add("PractitionerName", "");
        fields.Add("PractitionerFirmName", "");
        fields.Add("PractitionerAddress", "");
        fields.Add("PractitionerPostcode", "");
        fields.Add("PractitionerTelephone", "");
        fields.Add("InsolvencyServiceOffice", "London B");
        fields.Add("InsolvencyServiceContact", "Enquiry Desk");
        fields.Add("InsolvencyServiceAddress", "16th Floor, 1 Westfield Avenue, LONDON, United Kingdom");
        fields.Add("InsolvencyServicePostcode", "E20 1HZ");
        fields.Add("InsolvencyServiceTelephone", "0207 6371110");
        fields.Add("DateOfPreviousOrder", "");
        fields.Add("DeceasedDate", "");
        searchResult = new() { Fields = fields };
        searchResults.Add(searchResult);

        fields = [];
        fields.Add("Case_Indiv_No", "15139343_1");
        fields.Add("CaseNumber", "15139343");
        fields.Add("IndividualNumber", "1");
        fields.Add("GlobalSearchField", "15139343 1 Hants SO16 2JE");
        fields.Add("TradeNamesSearchField", "SEVEN-ELEVEN");
        fields.Add("LastNamesSearchField", "MAN");
        fields.Add("ForeNamesSearchField", "KAM PING");
        fields.Add("FirstName", "KAM PING");
        fields.Add("FamilyName", "MAN");
        fields.Add("Title", "Mrs");
        fields.Add("AlternativeNames", "No OtherNames Found");
        fields.Add("Gender", "Female");
        fields.Add("Occupation", "No Occupation Found");
        fields.Add("LastKnownTown", "Hants");
        fields.Add("LastKnownAddress", "65, High Road, Southampton, Hants");
        fields.Add("LastKnownPostcode", "SO16 2JE");
        fields.Add("AddressWithheld", "N");
        fields.Add("DateOfBirth", "No Date of Birth Found");
        fields.Add("CaseName", "KAM PING MAN");
        fields.Add("Court", "County Court at Southampton");
        fields.Add("CourtNumber", "0000015");
        fields.Add("CaseYear", "2000");
        fields.Add("InsolvencyType", "Bankruptcy");
        fields.Add("InsolvencyDate", "13/01/2000");
        fields.Add("NotificationDate", "0001-01-01T00:00:00Z");
        fields.Add("CaseStatus", "Discharge Suspended Indefinitely (from 12/06/2000)");
        fields.Add("CaseDescription", "Kam Ping Man, residential address unknown, trading at 65,High Road, Southampton, Hampshire SO16 2JE, as a proprietorof atake away food shop as Seven-Eleven Chinese Takeaway.");
        fields.Add("TradingData", "<Trading><TradingDetails><TradingName>SEVEN-ELEVEN</TradingName><TradingAddress>65 High Road, Southampton, Hampshire, SO16 2JE</TradingAddress></TradingDetails></Trading>");
        fields.Add("TradingNames", "SEVEN-ELEVEN");
        fields.Add("OtherForenames", "[]");
        fields.Add("OtherSurnames", "[]");
        fields.Add("HasRestrictions", "false");
        fields.Add("RestrictionsType", "");
        fields.Add("RestrictionsStartDate", "");
        fields.Add("RestrictionsEndDate", "");
        fields.Add("HasPrevInterimRestrictionsOrder", "false");
        fields.Add("PrevInterimRestrictionsOrderStartDate", "");
        fields.Add("PrevInterimRestrictionsOrderEndDate", "");
        fields.Add("PractitionerName", "");
        fields.Add("PractitionerFirmName", "");
        fields.Add("PractitionerAddress", "");
        fields.Add("PractitionerPostcode", "");
        fields.Add("PractitionerTelephone", "");
        fields.Add("InsolvencyServiceOffice", "Southampton");
        fields.Add("InsolvencyServiceContact", "Enquiry Desk");
        fields.Add("InsolvencyServiceAddress", "Spring Place, 105 Commercial Road, SOUTHAMPTON, United Kingdom");
        fields.Add("InsolvencyServicePostcode", "SO15 1EG");
        fields.Add("InsolvencyServiceTelephone", "023 8083 1600");
        fields.Add("DateOfPreviousOrder", "");
        fields.Add("DeceasedDate", "");
        searchResult = new() { Fields = fields };
        searchResults.Add(searchResult);

        fields = [];

        fields.Add("Case_Indiv_No", "704074939_709170361");
        fields.Add("CaseNumber", "704074939");
        fields.Add("IndividualNumber", "709170361");
        fields.Add("GlobalSearchField", "704074939 709170361 PE15 8EE");
        fields.Add("TradeNamesSearchField", "");
        fields.Add("LastNamesSearchField", "LORRAINE");
        fields.Add("ForeNamesSearchField", "MARK");
        fields.Add("FirstName", "MARK");
        fields.Add("FamilyName", "LORRAINE");
        fields.Add("Title", "Mr");
        fields.Add("AlternativeNames", "No OtherNames Found");
        fields.Add("Gender", "Male");
        fields.Add("Occupation", "No Occupation Found");
        fields.Add("LastKnownTown", "");
        fields.Add("LastKnownAddress", "2 Poplar Close, March, GBR");
        fields.Add("LastKnownPostcode", "PE15 8EE");
        fields.Add("AddressWithheld", "N");
        fields.Add("DateOfBirth", "26/07/1970");
        fields.Add("CaseName", "Mark Lorraine");
        fields.Add("Court", "Voluntary Liquidation Cases");
        fields.Add("CourtNumber", "");
        fields.Add("CaseYear", "(Case Year does not apply to IVA)");
        fields.Add("InsolvencyType", "Individual Voluntary Arrangement");
        fields.Add("InsolvencyDate", "15/02/2023");
        fields.Add("NotificationDate", "2023-02-21T00:00:00Z");
        fields.Add("CaseStatus", "Current");
        fields.Add("CaseDescription", "(Case Description does not apply to IVA)");
        fields.Add("TradingData", "<No Trading Names Found>");
        fields.Add("TradingNames", "");
        fields.Add("OtherForenames", "[]");
        fields.Add("OtherSurnames", "[]");
        fields.Add("HasRestrictions", "false");
        fields.Add("RestrictionsType", "");
        fields.Add("RestrictionsStartDate", "");
        fields.Add("RestrictionsEndDate", "");
        fields.Add("HasPrevInterimRestrictionsOrder", "false");
        fields.Add("PrevInterimRestrictionsOrderStartDate", "");
        fields.Add("PrevInterimRestrictionsOrderEndDate", "");
        fields.Add("PractitionerName", "RICHARD HILTON SAVAGE");
        fields.Add("PractitionerFirmName", "Financial Support Systems Ltd");
        fields.Add("PractitionerAddress", "1st Floor, Bridgewater House, 58-60 Whitworth Street, MANCHESTER, United Kingdom");
        fields.Add("PractitionerPostcode", "M1 6LT");
        fields.Add("PractitionerTelephone", "");
        fields.Add("InsolvencyServiceOffice", "The Insolvency Service");
        fields.Add("InsolvencyServiceContact", "Enquiry Desk");
        fields.Add("InsolvencyServiceAddress", "Cannon House, 18 Priory Queensway, Birmingham, United Kingdom");
        fields.Add("InsolvencyServicePostcode", "B4 6FD");
        fields.Add("InsolvencyServiceTelephone", "0303 003 1742");
        fields.Add("DateOfPreviousOrder", "");
        fields.Add("DeceasedDate", "");
        searchResult = new() { Fields = fields };
        searchResults.Add(searchResult);

        fields = [];
        fields.Add("Case_Indiv_No", "704105907_709229073");
        fields.Add("CaseNumber", "704105907");
        fields.Add("IndividualNumber", "709229073");
        fields.Add("GlobalSearchField", "704105907 709229073 SE9 5QG");
        fields.Add("TradeNamesSearchField", "");
        fields.Add("LastNamesSearchField", "LORRAINE");
        fields.Add("ForeNamesSearchField", "TINA");
        fields.Add("FirstName", "TINA");
        fields.Add("FamilyName", "LORRAINE");
        fields.Add("Title", "Mrs");
        fields.Add("AlternativeNames", "No OtherNames Found");
        fields.Add("Gender", "Female");
        fields.Add("Occupation", "No Occupation Found");
        fields.Add("LastKnownTown", "");
        fields.Add("LastKnownAddress", "284, Middle Park Avenue, London, GBR");
        fields.Add("LastKnownPostcode", "SE9 5QG");
        fields.Add("AddressWithheld", "N");
        fields.Add("DateOfBirth", "07/01/1980");
        fields.Add("CaseName", "Tina Lorraine");
        fields.Add("Court", "Voluntary Liquidation Cases");
        fields.Add("CourtNumber", "");
        fields.Add("CaseYear", "(Case Year does not apply to IVA)");
        fields.Add("InsolvencyType", "Individual Voluntary Arrangement");
        fields.Add("InsolvencyDate", "08/03/2023");
        fields.Add("NotificationDate", "2023-03-21T00:00:00Z");
        fields.Add("CaseStatus", "Current");
        fields.Add("CaseDescription", "(Case Description does not apply to IVA)");
        fields.Add("TradingData", "<No Trading Names Found>");
        fields.Add("TradingNames", "");
        fields.Add("OtherForenames", "[]");
        fields.Add("OtherSurnames", "[]");
        fields.Add("HasRestrictions", "false");
        fields.Add("RestrictionsType", "");
        fields.Add("RestrictionsStartDate", "");
        fields.Add("RestrictionsEndDate", "");
        fields.Add("HasPrevInterimRestrictionsOrder", "false");
        fields.Add("PrevInterimRestrictionsOrderStartDate", "");
        fields.Add("PrevInterimRestrictionsOrderEndDate", "");
        fields.Add("PractitionerName", "DAVID RANKIN");
        fields.Add("PractitionerFirmName", "CREDITFIX LIMITED");
        fields.Add("PractitionerAddress", "Floor 3, 4 West Regent Street, GLASGOW, United Kingdom");
        fields.Add("PractitionerPostcode", "G2 1RW");
        fields.Add("PractitionerTelephone", "");
        fields.Add("InsolvencyServiceOffice", "The Insolvency Service");
        fields.Add("InsolvencyServiceContact", "Enquiry Desk");
        fields.Add("InsolvencyServiceAddress", "Cannon House, 18 Priory Queensway, Birmingham, United Kingdom");
        fields.Add("InsolvencyServicePostcode", "B4 6FD");
        fields.Add("InsolvencyServiceTelephone", "0303 003 1742");
        fields.Add("DateOfPreviousOrder", "");
        fields.Add("DeceasedDate", "");
        searchResult = new() { Fields = fields };
        searchResults.Add(searchResult);

        return searchResults.ToArray();
    }
}