//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Schema: https://github.com/InsolvencyService/RedundancyUploadService/blob/develop/Insolvency.RedundancyUploadService.Common/Models/Schemas/RP14_Flattened.xsd

using System.Xml.Serialization;
using System.ComponentModel.DataAnnotations;

namespace Inss.Common.IPUpload.Employer.Spreadsheet;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application", IsNullable=false)]
public partial class RP14 {
    
    private RP14Header headerField;
    
    private string nameOfBusinessField;
    
    private string companyNumberField;
    
    private string companyAddrLine1Field;
    
    private string companyAddrLine2Field;
    
    private string companyAddrLine3Field;
    
    private string companyAddrLine4Field;
    
    private string companyAddrTownField;
    
    private string companyAddrCountyField;
    
    private string companyAddrPostcodeField;
    
    private string companyAddrCountryField;
    
    private System.DateTime incorporationDateField;
    
    private bool incorporationDateFieldSpecified;
    
    private string natureOfBusinessField;
    
    private PayeType pAYEField;
    
    private string sICCodeField;
    
    private RP14Directors directorsField;
    
    private RP14Shareholders shareholdersField;
    
    private RP14AssociatedCompanies associatedCompaniesField;
    
    private RP14Employees employeesField;
    
    private RP14InsolvencyDetails insolvencyDetailsField;
    
    private RP14TransferDetails transferDetailsField;
    
    private RP14PayRecordsContact payRecordsContactField;
    
    private RP14InsolvencyPractitioner insolvencyPractitionerField;
    
    /// <remarks/>
    public RP14Header Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    public string NameOfBusiness {
        get {
            return this.nameOfBusinessField;
        }
        set {
            this.nameOfBusinessField = value;
        }
    }
    
    public string CompanyNumber {
        get {
            return this.companyNumberField;
        }
        set {
            this.companyNumberField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyAddrLine1 {
        get {
            return this.companyAddrLine1Field;
        }
        set {
            this.companyAddrLine1Field = value;
        }
    }
    
    /// <remarks/>
    public string CompanyAddrLine2 {
        get {
            return this.companyAddrLine2Field;
        }
        set {
            this.companyAddrLine2Field = value;
        }
    }
    
    /// <remarks/>
    public string CompanyAddrLine3 {
        get {
            return this.companyAddrLine3Field;
        }
        set {
            this.companyAddrLine3Field = value;
        }
    }
    
    /// <remarks/>
    public string CompanyAddrLine4 {
        get {
            return this.companyAddrLine4Field;
        }
        set {
            this.companyAddrLine4Field = value;
        }
    }
    
    /// <remarks/>
    public string CompanyAddrTown {
        get {
            return this.companyAddrTownField;
        }
        set {
            this.companyAddrTownField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyAddrCounty {
        get {
            return this.companyAddrCountyField;
        }
        set {
            this.companyAddrCountyField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyAddrPostcode {
        get {
            return this.companyAddrPostcodeField;
        }
        set {
            this.companyAddrPostcodeField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyAddrCountry {
        get {
            return this.companyAddrCountryField;
        }
        set {
            this.companyAddrCountryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime IncorporationDate {
        get {
            return this.incorporationDateField;
        }
        set {
            this.incorporationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IncorporationDateSpecified {
        get {
            return this.incorporationDateFieldSpecified;
        }
        set {
            this.incorporationDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string NatureOfBusiness {
        get {
            return this.natureOfBusinessField;
        }
        set {
            this.natureOfBusinessField = value;
        }
    }
    
    /// <remarks/>
    public PayeType PAYE {
        get {
            return this.pAYEField;
        }
        set {
            this.pAYEField = value;
        }
    }
    
    public string SICCode {
        get {
            return this.sICCodeField;
        }
        set {
            this.sICCodeField = value;
        }
    }
    
    /// <remarks/>
    public RP14Directors Directors {
        get {
            return this.directorsField;
        }
        set {
            this.directorsField = value;
        }
    }
    
    /// <remarks/>
    public RP14Shareholders Shareholders {
        get {
            return this.shareholdersField;
        }
        set {
            this.shareholdersField = value;
        }
    }
    
    /// <remarks/>
    public RP14AssociatedCompanies AssociatedCompanies {
        get {
            return this.associatedCompaniesField;
        }
        set {
            this.associatedCompaniesField = value;
        }
    }
    
    /// <remarks/>
    public RP14Employees Employees {
        get {
            return this.employeesField;
        }
        set {
            this.employeesField = value;
        }
    }
    
    /// <remarks/>
    public RP14InsolvencyDetails InsolvencyDetails {
        get {
            return this.insolvencyDetailsField;
        }
        set {
            this.insolvencyDetailsField = value;
        }
    }
    
    /// <remarks/>
    public RP14TransferDetails TransferDetails {
        get {
            return this.transferDetailsField;
        }
        set {
            this.transferDetailsField = value;
        }
    }
    
    /// <remarks/>
    public RP14PayRecordsContact PayRecordsContact {
        get {
            return this.payRecordsContactField;
        }
        set {
            this.payRecordsContactField = value;
        }
    }
    
    /// <remarks/>
    public RP14InsolvencyPractitioner InsolvencyPractitioner {
        get {
            return this.insolvencyPractitionerField;
        }
        set {
            this.insolvencyPractitionerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14Header {
    
    private string caseReferenceField;
    
    private string dMSDocumentIDField;
    
    private string claimReferenceField;
    
    private string cHAMPDocumentIDField;
    
    private string sourceField;
    
    private string externalReferenceField;
    
    public string CaseReference {
        get {
            return this.caseReferenceField;
        }
        set {
            this.caseReferenceField = value;
        }
    }
    
    /// <remarks/>
    public string DMSDocumentID {
        get {
            return this.dMSDocumentIDField;
        }
        set {
            this.dMSDocumentIDField = value;
        }
    }
    
    /// <remarks/>
    public string ClaimReference {
        get {
            return this.claimReferenceField;
        }
        set {
            this.claimReferenceField = value;
        }
    }
    
    /// <remarks/>
    public string CHAMPDocumentID {
        get {
            return this.cHAMPDocumentIDField;
        }
        set {
            this.cHAMPDocumentIDField = value;
        }
    }
    
    /// <remarks/>
    public string Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    public string ExternalReference {
        get {
            return this.externalReferenceField;
        }
        set {
            this.externalReferenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class InsolvencyPractitionerType {
    
    private string iPRegistrationNumberField;
    
    private string iPFirmNameField;
    
    private string iPNameField;
    
    private string iPAddressLine1Field;
    
    private string iPAddressLine2Field;
    
    private string iPAddressLine3Field;
    
    private string iPAddressLine4Field;
    
    private string iPAddressTownField;
    
    private string iPAddressCountyField;
    
    private string iPAddressPostcodeField;
    
    private string iPAddressCountryField;
    
    private string iPTelephoneNumberField;
    
    private string iPEmailAddressField;
    
    /// <remarks/>
    public string IPRegistrationNumber {
        get {
            return this.iPRegistrationNumberField;
        }
        set {
            this.iPRegistrationNumberField = value;
        }
    }
    
    /// <remarks/>
    public string IPFirmName {
        get {
            return this.iPFirmNameField;
        }
        set {
            this.iPFirmNameField = value;
        }
    }
    
    /// <remarks/>
    public string IPName {
        get {
            return this.iPNameField;
        }
        set {
            this.iPNameField = value;
        }
    }
    
    /// <remarks/>
    public string IPAddressLine1 {
        get {
            return this.iPAddressLine1Field;
        }
        set {
            this.iPAddressLine1Field = value;
        }
    }
    
    /// <remarks/>
    public string IPAddressLine2 {
        get {
            return this.iPAddressLine2Field;
        }
        set {
            this.iPAddressLine2Field = value;
        }
    }
    
    /// <remarks/>
    public string IPAddressLine3 {
        get {
            return this.iPAddressLine3Field;
        }
        set {
            this.iPAddressLine3Field = value;
        }
    }
    
    /// <remarks/>
    public string IPAddressLine4 {
        get {
            return this.iPAddressLine4Field;
        }
        set {
            this.iPAddressLine4Field = value;
        }
    }
    
    /// <remarks/>
    public string IPAddressTown {
        get {
            return this.iPAddressTownField;
        }
        set {
            this.iPAddressTownField = value;
        }
    }
    
    /// <remarks/>
    public string IPAddressCounty {
        get {
            return this.iPAddressCountyField;
        }
        set {
            this.iPAddressCountyField = value;
        }
    }
    
    /// <remarks/>
    public string IPAddressPostcode {
        get {
            return this.iPAddressPostcodeField;
        }
        set {
            this.iPAddressPostcodeField = value;
        }
    }
    
    /// <remarks/>
    public string IPAddressCountry {
        get {
            return this.iPAddressCountryField;
        }
        set {
            this.iPAddressCountryField = value;
        }
    }
    
    /// <remarks/>
    public string IPTelephoneNumber {
        get {
            return this.iPTelephoneNumberField;
        }
        set {
            this.iPTelephoneNumberField = value;
        }
    }
    
    /// <remarks/>
    public string IPEmailAddress {
        get {
            return this.iPEmailAddressField;
        }
        set {
            this.iPEmailAddressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class NameType {
    
    private string surnameField;
    
    private string forenamesField;
    
    private string titleField;
    
    private string fullNameField;
    
    private string initialsField;
    
    /// <remarks/>
    public string Surname {
        get {
            return this.surnameField;
        }
        set {
            this.surnameField = value;
        }
    }
    
    /// <remarks/>
    public string Forenames {
        get {
            return this.forenamesField;
        }
        set {
            this.forenamesField = value;
        }
    }
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string FullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
    
    /// <remarks/>
    public string Initials {
        get {
            return this.initialsField;
        }
        set {
            this.initialsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class PayeType {
    
    private string districtField;
    
    private string referenceField;
    
    /// <remarks/>
    public string District {
        get {
            return this.districtField;
        }
        set {
            this.districtField = value;
        }
    }
    
    /// <remarks/>
    public string Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14Directors {
    
    private RP14DirectorsDirector1 director1Field;
    
    private RP14DirectorsDirector2 director2Field;
    
    private RP14DirectorsDirector3 director3Field;
    
    private RP14DirectorsDirector4 director4Field;
    
    private RP14DirectorsDirector5 director5Field;
    
    private RP14DirectorsDirector6 director6Field;
    
    private YesNoType claimingRPAsEmployeeField;
    
    private bool claimingRPAsEmployeeFieldSpecified;
    
    /// <remarks/>
    public RP14DirectorsDirector1 Director1 {
        get {
            return this.director1Field;
        }
        set {
            this.director1Field = value;
        }
    }
    
    /// <remarks/>
    public RP14DirectorsDirector2 Director2 {
        get {
            return this.director2Field;
        }
        set {
            this.director2Field = value;
        }
    }
    
    /// <remarks/>
    public RP14DirectorsDirector3 Director3 {
        get {
            return this.director3Field;
        }
        set {
            this.director3Field = value;
        }
    }
    
    /// <remarks/>
    public RP14DirectorsDirector4 Director4 {
        get {
            return this.director4Field;
        }
        set {
            this.director4Field = value;
        }
    }
    
    /// <remarks/>
    public RP14DirectorsDirector5 Director5 {
        get {
            return this.director5Field;
        }
        set {
            this.director5Field = value;
        }
    }
    
    /// <remarks/>
    public RP14DirectorsDirector6 Director6 {
        get {
            return this.director6Field;
        }
        set {
            this.director6Field = value;
        }
    }
    
    /// <remarks/>
    public YesNoType ClaimingRPAsEmployee {
        get {
            return this.claimingRPAsEmployeeField;
        }
        set {
            this.claimingRPAsEmployeeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ClaimingRPAsEmployeeSpecified {
        get {
            return this.claimingRPAsEmployeeFieldSpecified;
        }
        set {
            this.claimingRPAsEmployeeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14DirectorsDirector1 {
    
    private string director1SurnameField;
    
    private string director1ForenamesField;
    
    private string director1TitleField;
    
    private string director1FullNameField;
    
    private string director1InitialsField;
    
    private string director1NINOField;
    
    /// <remarks/>
    public string Director1Surname {
        get {
            return this.director1SurnameField;
        }
        set {
            this.director1SurnameField = value;
        }
    }
    
    /// <remarks/>
    public string Director1Forenames {
        get {
            return this.director1ForenamesField;
        }
        set {
            this.director1ForenamesField = value;
        }
    }
    
    /// <remarks/>
    public string Director1Title {
        get {
            return this.director1TitleField;
        }
        set {
            this.director1TitleField = value;
        }
    }
    
    /// <remarks/>
    public string Director1FullName {
        get {
            return this.director1FullNameField;
        }
        set {
            this.director1FullNameField = value;
        }
    }
    
    /// <remarks/>
    public string Director1Initials {
        get {
            return this.director1InitialsField;
        }
        set {
            this.director1InitialsField = value;
        }
    }
    
    public string Director1NINO {
        get {
            return this.director1NINOField;
        }
        set {
            this.director1NINOField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14DirectorsDirector2 {
    
    private string director2SurnameField;
    
    private string director2ForenamesField;
    
    private string director2TitleField;
    
    private string director2FullNameField;
    
    private string director2InitialsField;
    
    private string director2NINOField;
    
    /// <remarks/>
    public string Director2Surname {
        get {
            return this.director2SurnameField;
        }
        set {
            this.director2SurnameField = value;
        }
    }
    
    /// <remarks/>
    public string Director2Forenames {
        get {
            return this.director2ForenamesField;
        }
        set {
            this.director2ForenamesField = value;
        }
    }
    
    /// <remarks/>
    public string Director2Title {
        get {
            return this.director2TitleField;
        }
        set {
            this.director2TitleField = value;
        }
    }
    
    /// <remarks/>
    public string Director2FullName {
        get {
            return this.director2FullNameField;
        }
        set {
            this.director2FullNameField = value;
        }
    }
    
    /// <remarks/>
    public string Director2Initials {
        get {
            return this.director2InitialsField;
        }
        set {
            this.director2InitialsField = value;
        }
    }
    
    public string Director2NINO {
        get {
            return this.director2NINOField;
        }
        set {
            this.director2NINOField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14DirectorsDirector3 {
    
    private string director3SurnameField;
    
    private string director3ForenamesField;
    
    private string director3TitleField;
    
    private string director3FullNameField;
    
    private string director3InitialsField;
    
    private string director3NINOField;
    
    /// <remarks/>
    public string Director3Surname {
        get {
            return this.director3SurnameField;
        }
        set {
            this.director3SurnameField = value;
        }
    }
    
    /// <remarks/>
    public string Director3Forenames {
        get {
            return this.director3ForenamesField;
        }
        set {
            this.director3ForenamesField = value;
        }
    }
    
    /// <remarks/>
    public string Director3Title {
        get {
            return this.director3TitleField;
        }
        set {
            this.director3TitleField = value;
        }
    }
    
    /// <remarks/>
    public string Director3FullName {
        get {
            return this.director3FullNameField;
        }
        set {
            this.director3FullNameField = value;
        }
    }
    
    /// <remarks/>
    public string Director3Initials {
        get {
            return this.director3InitialsField;
        }
        set {
            this.director3InitialsField = value;
        }
    }
    
    public string Director3NINO {
        get {
            return this.director3NINOField;
        }
        set {
            this.director3NINOField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14DirectorsDirector4 {
    
    private string director4SurnameField;
    
    private string director4ForenamesField;
    
    private string director4TitleField;
    
    private string director4FullNameField;
    
    private string director4InitialsField;
    
    private string director4NINOField;
    
    /// <remarks/>
    public string Director4Surname {
        get {
            return this.director4SurnameField;
        }
        set {
            this.director4SurnameField = value;
        }
    }
    
    /// <remarks/>
    public string Director4Forenames {
        get {
            return this.director4ForenamesField;
        }
        set {
            this.director4ForenamesField = value;
        }
    }
    
    /// <remarks/>
    public string Director4Title {
        get {
            return this.director4TitleField;
        }
        set {
            this.director4TitleField = value;
        }
    }
    
    /// <remarks/>
    public string Director4FullName {
        get {
            return this.director4FullNameField;
        }
        set {
            this.director4FullNameField = value;
        }
    }
    
    /// <remarks/>
    public string Director4Initials {
        get {
            return this.director4InitialsField;
        }
        set {
            this.director4InitialsField = value;
        }
    }
    
    public string Director4NINO {
        get {
            return this.director4NINOField;
        }
        set {
            this.director4NINOField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14DirectorsDirector5 {
    
    private string director5SurnameField;
    
    private string director5ForenamesField;
    
    private string director5TitleField;
    
    private string director5FullNameField;
    
    private string director5InitialsField;
    
    private string director5NINOField;
    
    /// <remarks/>
    public string Director5Surname {
        get {
            return this.director5SurnameField;
        }
        set {
            this.director5SurnameField = value;
        }
    }
    
    /// <remarks/>
    public string Director5Forenames {
        get {
            return this.director5ForenamesField;
        }
        set {
            this.director5ForenamesField = value;
        }
    }
    
    /// <remarks/>
    public string Director5Title {
        get {
            return this.director5TitleField;
        }
        set {
            this.director5TitleField = value;
        }
    }
    
    /// <remarks/>
    public string Director5FullName {
        get {
            return this.director5FullNameField;
        }
        set {
            this.director5FullNameField = value;
        }
    }
    
    /// <remarks/>
    public string Director5Initials {
        get {
            return this.director5InitialsField;
        }
        set {
            this.director5InitialsField = value;
        }
    }
    
    public string Director5NINO {
        get {
            return this.director5NINOField;
        }
        set {
            this.director5NINOField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14DirectorsDirector6 {
    
    private string director6SurnameField;
    
    private string director6ForenamesField;
    
    private string director6TitleField;
    
    private string director6FullNameField;
    
    private string director6InitialsField;
    
    private string director6NINOField;
    
    /// <remarks/>
    public string Director6Surname {
        get {
            return this.director6SurnameField;
        }
        set {
            this.director6SurnameField = value;
        }
    }
    
    /// <remarks/>
    public string Director6Forenames {
        get {
            return this.director6ForenamesField;
        }
        set {
            this.director6ForenamesField = value;
        }
    }
    
    /// <remarks/>
    public string Director6Title {
        get {
            return this.director6TitleField;
        }
        set {
            this.director6TitleField = value;
        }
    }
    
    /// <remarks/>
    public string Director6FullName {
        get {
            return this.director6FullNameField;
        }
        set {
            this.director6FullNameField = value;
        }
    }
    
    /// <remarks/>
    public string Director6Initials {
        get {
            return this.director6InitialsField;
        }
        set {
            this.director6InitialsField = value;
        }
    }
    
    public string Director6NINO {
        get {
            return this.director6NINOField;
        }
        set {
            this.director6NINOField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public enum YesNoType {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14Shareholders {
    
    private RP14ShareholdersShareholder1 shareholder1Field;
    
    private RP14ShareholdersShareholder2 shareholder2Field;
    
    private RP14ShareholdersShareholder3 shareholder3Field;
    
    private RP14ShareholdersShareholder4 shareholder4Field;
    
    private RP14ShareholdersShareholder5 shareholder5Field;
    
    private RP14ShareholdersShareholder6 shareholder6Field;
    
    /// <remarks/>
    public RP14ShareholdersShareholder1 Shareholder1 {
        get {
            return this.shareholder1Field;
        }
        set {
            this.shareholder1Field = value;
        }
    }
    
    /// <remarks/>
    public RP14ShareholdersShareholder2 Shareholder2 {
        get {
            return this.shareholder2Field;
        }
        set {
            this.shareholder2Field = value;
        }
    }
    
    /// <remarks/>
    public RP14ShareholdersShareholder3 Shareholder3 {
        get {
            return this.shareholder3Field;
        }
        set {
            this.shareholder3Field = value;
        }
    }
    
    /// <remarks/>
    public RP14ShareholdersShareholder4 Shareholder4 {
        get {
            return this.shareholder4Field;
        }
        set {
            this.shareholder4Field = value;
        }
    }
    
    /// <remarks/>
    public RP14ShareholdersShareholder5 Shareholder5 {
        get {
            return this.shareholder5Field;
        }
        set {
            this.shareholder5Field = value;
        }
    }
    
    /// <remarks/>
    public RP14ShareholdersShareholder6 Shareholder6 {
        get {
            return this.shareholder6Field;
        }
        set {
            this.shareholder6Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14ShareholdersShareholder1 {
    
    private string shareholder1SurnameField;
    
    private string shareholder1ForenamesField;
    
    private string shareholder1TitleField;
    
    private string shareholder1FullNameField;
    
    private string shareholder1InitialsField;
    
    private string shareholder1NoOfSharesHeldField;
    
    private decimal shareholder1PercentageField;
    
    private bool shareholder1PercentageFieldSpecified;
    
    /// <remarks/>
    public string Shareholder1Surname {
        get {
            return this.shareholder1SurnameField;
        }
        set {
            this.shareholder1SurnameField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder1Forenames {
        get {
            return this.shareholder1ForenamesField;
        }
        set {
            this.shareholder1ForenamesField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder1Title {
        get {
            return this.shareholder1TitleField;
        }
        set {
            this.shareholder1TitleField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder1FullName {
        get {
            return this.shareholder1FullNameField;
        }
        set {
            this.shareholder1FullNameField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder1Initials {
        get {
            return this.shareholder1InitialsField;
        }
        set {
            this.shareholder1InitialsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Shareholder1NoOfSharesHeld {
        get {
            return this.shareholder1NoOfSharesHeldField;
        }
        set {
            this.shareholder1NoOfSharesHeldField = value;
        }
    }
    
    public decimal Shareholder1Percentage {
        get {
            return this.shareholder1PercentageField;
        }
        set {
            this.shareholder1PercentageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Shareholder1PercentageSpecified {
        get {
            return this.shareholder1PercentageFieldSpecified;
        }
        set {
            this.shareholder1PercentageFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14ShareholdersShareholder2 {
    
    private string shareholder2SurnameField;
    
    private string shareholder2ForenamesField;
    
    private string shareholder2TitleField;
    
    private string shareholder2FullNameField;
    
    private string shareholder2InitialsField;
    
    private string shareholder2NoOfSharesHeldField;
    
    private decimal shareholder2PercentageField;
    
    private bool shareholder2PercentageFieldSpecified;
    
    /// <remarks/>
    public string Shareholder2Surname {
        get {
            return this.shareholder2SurnameField;
        }
        set {
            this.shareholder2SurnameField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder2Forenames {
        get {
            return this.shareholder2ForenamesField;
        }
        set {
            this.shareholder2ForenamesField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder2Title {
        get {
            return this.shareholder2TitleField;
        }
        set {
            this.shareholder2TitleField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder2FullName {
        get {
            return this.shareholder2FullNameField;
        }
        set {
            this.shareholder2FullNameField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder2Initials {
        get {
            return this.shareholder2InitialsField;
        }
        set {
            this.shareholder2InitialsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Shareholder2NoOfSharesHeld {
        get {
            return this.shareholder2NoOfSharesHeldField;
        }
        set {
            this.shareholder2NoOfSharesHeldField = value;
        }
    }
    
    public decimal Shareholder2Percentage {
        get {
            return this.shareholder2PercentageField;
        }
        set {
            this.shareholder2PercentageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Shareholder2PercentageSpecified {
        get {
            return this.shareholder2PercentageFieldSpecified;
        }
        set {
            this.shareholder2PercentageFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14ShareholdersShareholder3 {
    
    private string shareholder3SurnameField;
    
    private string shareholder3ForenamesField;
    
    private string shareholder3TitleField;
    
    private string shareholder3FullNameField;
    
    private string shareholder3InitialsField;
    
    private string shareholder3NoOfSharesHeldField;
    
    private decimal shareholder3PercentageField;
    
    private bool shareholder3PercentageFieldSpecified;
    
    /// <remarks/>
    public string Shareholder3Surname {
        get {
            return this.shareholder3SurnameField;
        }
        set {
            this.shareholder3SurnameField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder3Forenames {
        get {
            return this.shareholder3ForenamesField;
        }
        set {
            this.shareholder3ForenamesField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder3Title {
        get {
            return this.shareholder3TitleField;
        }
        set {
            this.shareholder3TitleField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder3FullName {
        get {
            return this.shareholder3FullNameField;
        }
        set {
            this.shareholder3FullNameField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder3Initials {
        get {
            return this.shareholder3InitialsField;
        }
        set {
            this.shareholder3InitialsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Shareholder3NoOfSharesHeld {
        get {
            return this.shareholder3NoOfSharesHeldField;
        }
        set {
            this.shareholder3NoOfSharesHeldField = value;
        }
    }
    
    public decimal Shareholder3Percentage {
        get {
            return this.shareholder3PercentageField;
        }
        set {
            this.shareholder3PercentageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Shareholder3PercentageSpecified {
        get {
            return this.shareholder3PercentageFieldSpecified;
        }
        set {
            this.shareholder3PercentageFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14ShareholdersShareholder4 {
    
    private string shareholder4SurnameField;
    
    private string shareholder4ForenamesField;
    
    private string shareholder4TitleField;
    
    private string shareholder4FullNameField;
    
    private string shareholder4InitialsField;
    
    private string shareholder4NoOfSharesHeldField;
    
    private decimal shareholder4PercentageField;
    
    private bool shareholder4PercentageFieldSpecified;
    
    /// <remarks/>
    public string Shareholder4Surname {
        get {
            return this.shareholder4SurnameField;
        }
        set {
            this.shareholder4SurnameField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder4Forenames {
        get {
            return this.shareholder4ForenamesField;
        }
        set {
            this.shareholder4ForenamesField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder4Title {
        get {
            return this.shareholder4TitleField;
        }
        set {
            this.shareholder4TitleField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder4FullName {
        get {
            return this.shareholder4FullNameField;
        }
        set {
            this.shareholder4FullNameField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder4Initials {
        get {
            return this.shareholder4InitialsField;
        }
        set {
            this.shareholder4InitialsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Shareholder4NoOfSharesHeld {
        get {
            return this.shareholder4NoOfSharesHeldField;
        }
        set {
            this.shareholder4NoOfSharesHeldField = value;
        }
    }
    
    public decimal Shareholder4Percentage {
        get {
            return this.shareholder4PercentageField;
        }
        set {
            this.shareholder4PercentageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Shareholder4PercentageSpecified {
        get {
            return this.shareholder4PercentageFieldSpecified;
        }
        set {
            this.shareholder4PercentageFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14ShareholdersShareholder5 {
    
    private string shareholder5SurnameField;
    
    private string shareholder5ForenamesField;
    
    private string shareholder5TitleField;
    
    private string shareholder5FullNameField;
    
    private string shareholder5InitialsField;
    
    private string shareholder5NoOfSharesHeldField;
    
    private decimal shareholder5PercentageField;
    
    private bool shareholder5PercentageFieldSpecified;
    
    /// <remarks/>
    public string Shareholder5Surname {
        get {
            return this.shareholder5SurnameField;
        }
        set {
            this.shareholder5SurnameField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder5Forenames {
        get {
            return this.shareholder5ForenamesField;
        }
        set {
            this.shareholder5ForenamesField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder5Title {
        get {
            return this.shareholder5TitleField;
        }
        set {
            this.shareholder5TitleField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder5FullName {
        get {
            return this.shareholder5FullNameField;
        }
        set {
            this.shareholder5FullNameField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder5Initials {
        get {
            return this.shareholder5InitialsField;
        }
        set {
            this.shareholder5InitialsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Shareholder5NoOfSharesHeld {
        get {
            return this.shareholder5NoOfSharesHeldField;
        }
        set {
            this.shareholder5NoOfSharesHeldField = value;
        }
    }
    
    public decimal Shareholder5Percentage {
        get {
            return this.shareholder5PercentageField;
        }
        set {
            this.shareholder5PercentageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Shareholder5PercentageSpecified {
        get {
            return this.shareholder5PercentageFieldSpecified;
        }
        set {
            this.shareholder5PercentageFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14ShareholdersShareholder6 {
    
    private string shareholder6SurnameField;
    
    private string shareholder6ForenamesField;
    
    private string shareholder6TitleField;
    
    private string shareholder6FullNameField;
    
    private string shareholder6InitialsField;
    
    private string shareholder6NoOfSharesHeldField;
    
    private decimal shareholder6PercentageField;
    
    private bool shareholder6PercentageFieldSpecified;
    
    /// <remarks/>
    public string Shareholder6Surname {
        get {
            return this.shareholder6SurnameField;
        }
        set {
            this.shareholder6SurnameField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder6Forenames {
        get {
            return this.shareholder6ForenamesField;
        }
        set {
            this.shareholder6ForenamesField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder6Title {
        get {
            return this.shareholder6TitleField;
        }
        set {
            this.shareholder6TitleField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder6FullName {
        get {
            return this.shareholder6FullNameField;
        }
        set {
            this.shareholder6FullNameField = value;
        }
    }
    
    /// <remarks/>
    public string Shareholder6Initials {
        get {
            return this.shareholder6InitialsField;
        }
        set {
            this.shareholder6InitialsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Shareholder6NoOfSharesHeld {
        get {
            return this.shareholder6NoOfSharesHeldField;
        }
        set {
            this.shareholder6NoOfSharesHeldField = value;
        }
    }
    
    public decimal Shareholder6Percentage {
        get {
            return this.shareholder6PercentageField;
        }
        set {
            this.shareholder6PercentageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Shareholder6PercentageSpecified {
        get {
            return this.shareholder6PercentageFieldSpecified;
        }
        set {
            this.shareholder6PercentageFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14AssociatedCompanies {
    
    private YesNoType legallyAssociatedCompaniesField;
    
    private bool legallyAssociatedCompaniesFieldSpecified;
    
    private RP14AssociatedCompaniesAssociatedCompany1 associatedCompany1Field;
    
    private RP14AssociatedCompaniesAssociatedCompany2 associatedCompany2Field;
    
    /// <remarks/>
    public YesNoType LegallyAssociatedCompanies {
        get {
            return this.legallyAssociatedCompaniesField;
        }
        set {
            this.legallyAssociatedCompaniesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LegallyAssociatedCompaniesSpecified {
        get {
            return this.legallyAssociatedCompaniesFieldSpecified;
        }
        set {
            this.legallyAssociatedCompaniesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public RP14AssociatedCompaniesAssociatedCompany1 AssociatedCompany1 {
        get {
            return this.associatedCompany1Field;
        }
        set {
            this.associatedCompany1Field = value;
        }
    }
    
    /// <remarks/>
    public RP14AssociatedCompaniesAssociatedCompany2 AssociatedCompany2 {
        get {
            return this.associatedCompany2Field;
        }
        set {
            this.associatedCompany2Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14AssociatedCompaniesAssociatedCompany1 {
    
    private string assocCompany1NameField;
    
    private string assocCompany1NumberField;
    
    private string assocComp1AddrLine1Field;
    
    private string assocComp1AddrLine2Field;
    
    private string assocComp1AddrLine3Field;
    
    private string assocComp1AddrLine4Field;
    
    private string assocComp1AddrTownField;
    
    private string assocComp1AddrCountyField;
    
    private string assocComp1AddrPostcodeField;
    
    private string assocComp1AddrCountryField;
    
    private RP14AssociatedCompaniesAssociatedCompany1AssocComp1OfferToEmployEmployees assocComp1OfferToEmployEmployeesField;
    
    private string assocComp1ReasonForAssociationField;
    
    public string AssocCompany1Name {
        get {
            return this.assocCompany1NameField;
        }
        set {
            this.assocCompany1NameField = value;
        }
    }
    
    /// <remarks/>
    public string AssocCompany1Number {
        get {
            return this.assocCompany1NumberField;
        }
        set {
            this.assocCompany1NumberField = value;
        }
    }
    
    /// <remarks/>
    public string AssocComp1AddrLine1 {
        get {
            return this.assocComp1AddrLine1Field;
        }
        set {
            this.assocComp1AddrLine1Field = value;
        }
    }
    
    /// <remarks/>
    public string AssocComp1AddrLine2 {
        get {
            return this.assocComp1AddrLine2Field;
        }
        set {
            this.assocComp1AddrLine2Field = value;
        }
    }
    
    /// <remarks/>
    public string AssocComp1AddrLine3 {
        get {
            return this.assocComp1AddrLine3Field;
        }
        set {
            this.assocComp1AddrLine3Field = value;
        }
    }
    
    /// <remarks/>
    public string AssocComp1AddrLine4 {
        get {
            return this.assocComp1AddrLine4Field;
        }
        set {
            this.assocComp1AddrLine4Field = value;
        }
    }
    
    /// <remarks/>
    public string AssocComp1AddrTown {
        get {
            return this.assocComp1AddrTownField;
        }
        set {
            this.assocComp1AddrTownField = value;
        }
    }
    
    /// <remarks/>
    public string AssocComp1AddrCounty {
        get {
            return this.assocComp1AddrCountyField;
        }
        set {
            this.assocComp1AddrCountyField = value;
        }
    }
    
    /// <remarks/>
    public string AssocComp1AddrPostcode {
        get {
            return this.assocComp1AddrPostcodeField;
        }
        set {
            this.assocComp1AddrPostcodeField = value;
        }
    }
    
    /// <remarks/>
    public string AssocComp1AddrCountry {
        get {
            return this.assocComp1AddrCountryField;
        }
        set {
            this.assocComp1AddrCountryField = value;
        }
    }
    
    /// <remarks/>
    public RP14AssociatedCompaniesAssociatedCompany1AssocComp1OfferToEmployEmployees AssocComp1OfferToEmployEmployees {
        get {
            return this.assocComp1OfferToEmployEmployeesField;
        }
        set {
            this.assocComp1OfferToEmployEmployeesField = value;
        }
    }
    
    public string AssocComp1ReasonForAssociation {
        get {
            return this.assocComp1ReasonForAssociationField;
        }
        set {
            this.assocComp1ReasonForAssociationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14AssociatedCompaniesAssociatedCompany1AssocComp1OfferToEmployEmployees {
    
    private YesNoType assocComp1OfferMadeField;
    
    private object assocComp1DetailsOfOfferField;
    
    /// <remarks/>
    public YesNoType AssocComp1OfferMade {
        get {
            return this.assocComp1OfferMadeField;
        }
        set {
            this.assocComp1OfferMadeField = value;
        }
    }
    
    /// <remarks/>
    public object AssocComp1DetailsOfOffer {
        get {
            return this.assocComp1DetailsOfOfferField;
        }
        set {
            this.assocComp1DetailsOfOfferField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14AssociatedCompaniesAssociatedCompany2 {
    
    private string assocCompany2NameField;
    
    private string assocCompany2NumberField;
    
    private string assocComp2AddrLine1Field;
    
    private string assocComp2AddrLine2Field;
    
    private string assocComp2AddrLine3Field;
    
    private string assocComp2AddrLine4Field;
    
    private string assocComp2AddrTownField;
    
    private string assocComp2AddrCountyField;
    
    private string assocComp2AddrPostcodeField;
    
    private string assocComp2AddrCountryField;
    
    private RP14AssociatedCompaniesAssociatedCompany2AssocComp2OfferToEmployEmployees assocComp2OfferToEmployEmployeesField;
    
    private string assocComp2ReasonForAssociationField;
    
    public string AssocCompany2Name {
        get {
            return this.assocCompany2NameField;
        }
        set {
            this.assocCompany2NameField = value;
        }
    }
    
    /// <remarks/>
    public string AssocCompany2Number {
        get {
            return this.assocCompany2NumberField;
        }
        set {
            this.assocCompany2NumberField = value;
        }
    }
    
    /// <remarks/>
    public string AssocComp2AddrLine1 {
        get {
            return this.assocComp2AddrLine1Field;
        }
        set {
            this.assocComp2AddrLine1Field = value;
        }
    }
    
    /// <remarks/>
    public string AssocComp2AddrLine2 {
        get {
            return this.assocComp2AddrLine2Field;
        }
        set {
            this.assocComp2AddrLine2Field = value;
        }
    }
    
    /// <remarks/>
    public string AssocComp2AddrLine3 {
        get {
            return this.assocComp2AddrLine3Field;
        }
        set {
            this.assocComp2AddrLine3Field = value;
        }
    }
    
    /// <remarks/>
    public string AssocComp2AddrLine4 {
        get {
            return this.assocComp2AddrLine4Field;
        }
        set {
            this.assocComp2AddrLine4Field = value;
        }
    }
    
    /// <remarks/>
    public string AssocComp2AddrTown {
        get {
            return this.assocComp2AddrTownField;
        }
        set {
            this.assocComp2AddrTownField = value;
        }
    }
    
    /// <remarks/>
    public string AssocComp2AddrCounty {
        get {
            return this.assocComp2AddrCountyField;
        }
        set {
            this.assocComp2AddrCountyField = value;
        }
    }
    
    /// <remarks/>
    public string AssocComp2AddrPostcode {
        get {
            return this.assocComp2AddrPostcodeField;
        }
        set {
            this.assocComp2AddrPostcodeField = value;
        }
    }
    
    /// <remarks/>
    public string AssocComp2AddrCountry {
        get {
            return this.assocComp2AddrCountryField;
        }
        set {
            this.assocComp2AddrCountryField = value;
        }
    }
    
    /// <remarks/>
    public RP14AssociatedCompaniesAssociatedCompany2AssocComp2OfferToEmployEmployees AssocComp2OfferToEmployEmployees {
        get {
            return this.assocComp2OfferToEmployEmployeesField;
        }
        set {
            this.assocComp2OfferToEmployEmployeesField = value;
        }
    }
    
    public string AssocComp2ReasonForAssociation {
        get {
            return this.assocComp2ReasonForAssociationField;
        }
        set {
            this.assocComp2ReasonForAssociationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14AssociatedCompaniesAssociatedCompany2AssocComp2OfferToEmployEmployees {
    
    private YesNoType assocComp2OfferMadeField;
    
    private object assocComp2DetailsOfOfferField;
    
    /// <remarks/>
    public YesNoType AssocComp2OfferMade {
        get {
            return this.assocComp2OfferMadeField;
        }
        set {
            this.assocComp2OfferMadeField = value;
        }
    }
    
    /// <remarks/>
    public object AssocComp2DetailsOfOffer {
        get {
            return this.assocComp2DetailsOfOfferField;
        }
        set {
            this.assocComp2DetailsOfOfferField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14Employees {
    
    private string noOfEmployeesField;
    
    private RP14EmployeesEmployeesClaimingContinuity employeesClaimingContinuityField;
    
    private YesNoType strikesField;
    
    private bool strikesFieldSpecified;
    
    private YesNoType carryOverHolidayEntitlementField;
    
    private bool carryOverHolidayEntitlementFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NoOfEmployees {
        get {
            return this.noOfEmployeesField;
        }
        set {
            this.noOfEmployeesField = value;
        }
    }
    
    /// <remarks/>
    public RP14EmployeesEmployeesClaimingContinuity EmployeesClaimingContinuity {
        get {
            return this.employeesClaimingContinuityField;
        }
        set {
            this.employeesClaimingContinuityField = value;
        }
    }
    
    /// <remarks/>
    public YesNoType Strikes {
        get {
            return this.strikesField;
        }
        set {
            this.strikesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StrikesSpecified {
        get {
            return this.strikesFieldSpecified;
        }
        set {
            this.strikesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public YesNoType CarryOverHolidayEntitlement {
        get {
            return this.carryOverHolidayEntitlementField;
        }
        set {
            this.carryOverHolidayEntitlementField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CarryOverHolidayEntitlementSpecified {
        get {
            return this.carryOverHolidayEntitlementFieldSpecified;
        }
        set {
            this.carryOverHolidayEntitlementFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14EmployeesEmployeesClaimingContinuity {
    
    private YesNoType claimingContinuityField;
    
    private bool claimingContinuityFieldSpecified;
    
    private string employerNameField;
    
    private string employerAddrLine1Field;
    
    private string employerAddrLine2Field;
    
    private string employerAddrLine3Field;
    
    private string employerAddrLine4Field;
    
    private string employerAddrTownField;
    
    private string employerAddrCountyField;
    
    private string employerAddrPostcodeField;
    
    private string employerAddrCountryField;
    
    private System.DateTime tradingDateField;
    
    private bool tradingDateFieldSpecified;
    
    private YesNoType shouldClaimsBeAcceptedField;
    
    private bool shouldClaimsBeAcceptedFieldSpecified;
    
    /// <remarks/>
    public YesNoType ClaimingContinuity {
        get {
            return this.claimingContinuityField;
        }
        set {
            this.claimingContinuityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ClaimingContinuitySpecified {
        get {
            return this.claimingContinuityFieldSpecified;
        }
        set {
            this.claimingContinuityFieldSpecified = value;
        }
    }
    
    public string EmployerName {
        get {
            return this.employerNameField;
        }
        set {
            this.employerNameField = value;
        }
    }
    
    /// <remarks/>
    public string EmployerAddrLine1 {
        get {
            return this.employerAddrLine1Field;
        }
        set {
            this.employerAddrLine1Field = value;
        }
    }
    
    /// <remarks/>
    public string EmployerAddrLine2 {
        get {
            return this.employerAddrLine2Field;
        }
        set {
            this.employerAddrLine2Field = value;
        }
    }
    
    /// <remarks/>
    public string EmployerAddrLine3 {
        get {
            return this.employerAddrLine3Field;
        }
        set {
            this.employerAddrLine3Field = value;
        }
    }
    
    /// <remarks/>
    public string EmployerAddrLine4 {
        get {
            return this.employerAddrLine4Field;
        }
        set {
            this.employerAddrLine4Field = value;
        }
    }
    
    /// <remarks/>
    public string EmployerAddrTown {
        get {
            return this.employerAddrTownField;
        }
        set {
            this.employerAddrTownField = value;
        }
    }
    
    /// <remarks/>
    public string EmployerAddrCounty {
        get {
            return this.employerAddrCountyField;
        }
        set {
            this.employerAddrCountyField = value;
        }
    }
    
    /// <remarks/>
    public string EmployerAddrPostcode {
        get {
            return this.employerAddrPostcodeField;
        }
        set {
            this.employerAddrPostcodeField = value;
        }
    }
    
    /// <remarks/>
    public string EmployerAddrCountry {
        get {
            return this.employerAddrCountryField;
        }
        set {
            this.employerAddrCountryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime TradingDate {
        get {
            return this.tradingDateField;
        }
        set {
            this.tradingDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TradingDateSpecified {
        get {
            return this.tradingDateFieldSpecified;
        }
        set {
            this.tradingDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public YesNoType ShouldClaimsBeAccepted {
        get {
            return this.shouldClaimsBeAcceptedField;
        }
        set {
            this.shouldClaimsBeAcceptedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ShouldClaimsBeAcceptedSpecified {
        get {
            return this.shouldClaimsBeAcceptedFieldSpecified;
        }
        set {
            this.shouldClaimsBeAcceptedFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14InsolvencyDetails {
    
    private System.DateTime insolvencyDateField;
    
    private bool insolvencyDateFieldSpecified;
    
    private string insolvencyTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime InsolvencyDate {
        get {
            return this.insolvencyDateField;
        }
        set {
            this.insolvencyDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InsolvencyDateSpecified {
        get {
            return this.insolvencyDateFieldSpecified;
        }
        set {
            this.insolvencyDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string InsolvencyType {
        get {
            return this.insolvencyTypeField;
        }
        set {
            this.insolvencyTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14TransferDetails {
    
    private RP14TransferDetailsTransferType transferTypeField;
    
    private bool transferTypeFieldSpecified;
    
    private RP14TransferDetailsTransferTo transferToField;
    
    private System.DateTime transferDateField;
    
    private bool transferDateFieldSpecified;
    
    private System.DateTime negotiationDateField;
    
    private bool negotiationDateFieldSpecified;
    
    /// <remarks/>
    public RP14TransferDetailsTransferType TransferType {
        get {
            return this.transferTypeField;
        }
        set {
            this.transferTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TransferTypeSpecified {
        get {
            return this.transferTypeFieldSpecified;
        }
        set {
            this.transferTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public RP14TransferDetailsTransferTo TransferTo {
        get {
            return this.transferToField;
        }
        set {
            this.transferToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime TransferDate {
        get {
            return this.transferDateField;
        }
        set {
            this.transferDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TransferDateSpecified {
        get {
            return this.transferDateFieldSpecified;
        }
        set {
            this.transferDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime NegotiationDate {
        get {
            return this.negotiationDateField;
        }
        set {
            this.negotiationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NegotiationDateSpecified {
        get {
            return this.negotiationDateFieldSpecified;
        }
        set {
            this.negotiationDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public enum RP14TransferDetailsTransferType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("asset only")]
    assetonly,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("whole business")]
    wholebusiness,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("part of business")]
    partofbusiness,
    
    /// <remarks/>
    other,
    
    /// <remarks/>
    none,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14TransferDetailsTransferTo {
    
    private string nameField;
    
    private string transferToAddrLine1Field;
    
    private string transferToAddrLine2Field;
    
    private string transferToAddrLine3Field;
    
    private string transferToAddrLine4Field;
    
    private string transferToAddrTownField;
    
    private string transferToAddrCountyField;
    
    private string transferToAddrPostcodeField;
    
    private string transferToAddrCountryField;
    
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string TransferToAddrLine1 {
        get {
            return this.transferToAddrLine1Field;
        }
        set {
            this.transferToAddrLine1Field = value;
        }
    }
    
    /// <remarks/>
    public string TransferToAddrLine2 {
        get {
            return this.transferToAddrLine2Field;
        }
        set {
            this.transferToAddrLine2Field = value;
        }
    }
    
    /// <remarks/>
    public string TransferToAddrLine3 {
        get {
            return this.transferToAddrLine3Field;
        }
        set {
            this.transferToAddrLine3Field = value;
        }
    }
    
    /// <remarks/>
    public string TransferToAddrLine4 {
        get {
            return this.transferToAddrLine4Field;
        }
        set {
            this.transferToAddrLine4Field = value;
        }
    }
    
    /// <remarks/>
    public string TransferToAddrTown {
        get {
            return this.transferToAddrTownField;
        }
        set {
            this.transferToAddrTownField = value;
        }
    }
    
    /// <remarks/>
    public string TransferToAddrCounty {
        get {
            return this.transferToAddrCountyField;
        }
        set {
            this.transferToAddrCountyField = value;
        }
    }
    
    /// <remarks/>
    public string TransferToAddrPostcode {
        get {
            return this.transferToAddrPostcodeField;
        }
        set {
            this.transferToAddrPostcodeField = value;
        }
    }
    
    /// <remarks/>
    public string TransferToAddrCountry {
        get {
            return this.transferToAddrCountryField;
        }
        set {
            this.transferToAddrCountryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14PayRecordsContact {
    
    private string nameField;
    
    private string payRecordsAddrLine1Field;
    
    private string payRecordsAddrLine2Field;
    
    private string payRecordsAddrLine3Field;
    
    private string payRecordsAddrLine4Field;
    
    private string payRecordsAddrTownField;
    
    private string payRecordsAddrCountyField;
    
    private string payRecordsAddrPostcodeField;
    
    private string payRecordsAddrCountryField;
    
    private string payRecordsPhoneNumberField;
    
    private string payRecordsEmailAddressField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string PayRecordsAddrLine1 {
        get {
            return this.payRecordsAddrLine1Field;
        }
        set {
            this.payRecordsAddrLine1Field = value;
        }
    }
    
    /// <remarks/>
    public string PayRecordsAddrLine2 {
        get {
            return this.payRecordsAddrLine2Field;
        }
        set {
            this.payRecordsAddrLine2Field = value;
        }
    }
    
    /// <remarks/>
    public string PayRecordsAddrLine3 {
        get {
            return this.payRecordsAddrLine3Field;
        }
        set {
            this.payRecordsAddrLine3Field = value;
        }
    }
    
    /// <remarks/>
    public string PayRecordsAddrLine4 {
        get {
            return this.payRecordsAddrLine4Field;
        }
        set {
            this.payRecordsAddrLine4Field = value;
        }
    }
    
    /// <remarks/>
    public string PayRecordsAddrTown {
        get {
            return this.payRecordsAddrTownField;
        }
        set {
            this.payRecordsAddrTownField = value;
        }
    }
    
    /// <remarks/>
    public string PayRecordsAddrCounty {
        get {
            return this.payRecordsAddrCountyField;
        }
        set {
            this.payRecordsAddrCountyField = value;
        }
    }
    
    /// <remarks/>
    public string PayRecordsAddrPostcode {
        get {
            return this.payRecordsAddrPostcodeField;
        }
        set {
            this.payRecordsAddrPostcodeField = value;
        }
    }
    
    /// <remarks/>
    public string PayRecordsAddrCountry {
        get {
            return this.payRecordsAddrCountryField;
        }
        set {
            this.payRecordsAddrCountryField = value;
        }
    }
    
    public string PayRecordsPhoneNumber {
        get {
            return this.payRecordsPhoneNumberField;
        }
        set {
            this.payRecordsPhoneNumberField = value;
        }
    }
    
    /// <remarks/>
    public string PayRecordsEmailAddress {
        get {
            return this.payRecordsEmailAddressField;
        }
        set {
            this.payRecordsEmailAddressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ins.gsi.gov.uk/FileUpload/RP14_Application")]
public partial class RP14InsolvencyPractitioner : InsolvencyPractitionerType {
    
    private bool declarationAgreementField;
    
    /// <remarks/>
    public bool DeclarationAgreement {
        get {
            return this.declarationAgreementField;
        }
        set {
            this.declarationAgreementField = value;
        }
    }
}