//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Schema: https://github.com/InsolvencyService/RedundancyUploadService/blob/develop/Insolvency.RedundancyUploadService.Common/Models/Schemas/RP14.xsd

using System.Xml.Serialization;
using System.ComponentModel.DataAnnotations;

namespace Inss.Common.IPUpload.Employer.Api;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.inss.gsi.gov.uk/RP14_Application")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="www.inss.gsi.gov.uk/RP14_Application", IsNullable=false)]
public partial class RP14 {
    
    private RP14Header headerField;
    
    private string nameOfBusinessField;
    
    private string companyNumberField;
    
    private AddressType addressField;
    
    private System.DateTime incorporationDateField;
    
    private bool incorporationDateFieldSpecified;
    
    private string natureOfBusinessField;
    
    private PayeType pAYEField;
    
    private string sICCodeField;
    
    private RP14Directors directorsField;
    
    private RP14Shareholder[] shareholdersField;
    
    private RP14AssociatedCompanies associatedCompaniesField;
    
    private RP14Employees employeesField;
    
    private RP14InsolvencyDetails insolvencyDetailsField;
    
    private RP14TransferDetails transferDetailsField;
    
    private RP14PayRecordsContact payRecordsContactField;
    
    private RP14InsolvencyPractitioner insolvencyPractitionerField;
    
    /// <remarks/>
    public RP14Header Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    public string NameOfBusiness {
        get {
            return this.nameOfBusinessField;
        }
        set {
            this.nameOfBusinessField = value;
        }
    }
    
    public string CompanyNumber {
        get {
            return this.companyNumberField;
        }
        set {
            this.companyNumberField = value;
        }
    }
    
    /// <remarks/>
    public AddressType Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime IncorporationDate {
        get {
            return this.incorporationDateField;
        }
        set {
            this.incorporationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IncorporationDateSpecified {
        get {
            return this.incorporationDateFieldSpecified;
        }
        set {
            this.incorporationDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string NatureOfBusiness {
        get {
            return this.natureOfBusinessField;
        }
        set {
            this.natureOfBusinessField = value;
        }
    }
    
    /// <remarks/>
    public PayeType PAYE {
        get {
            return this.pAYEField;
        }
        set {
            this.pAYEField = value;
        }
    }
    
    public string SICCode {
        get {
            return this.sICCodeField;
        }
        set {
            this.sICCodeField = value;
        }
    }
    
    /// <remarks/>
    public RP14Directors Directors {
        get {
            return this.directorsField;
        }
        set {
            this.directorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Shareholder", IsNullable=false)]
    public RP14Shareholder[] Shareholders {
        get {
            return this.shareholdersField;
        }
        set {
            this.shareholdersField = value;
        }
    }
    
    /// <remarks/>
    public RP14AssociatedCompanies AssociatedCompanies {
        get {
            return this.associatedCompaniesField;
        }
        set {
            this.associatedCompaniesField = value;
        }
    }
    
    /// <remarks/>
    public RP14Employees Employees {
        get {
            return this.employeesField;
        }
        set {
            this.employeesField = value;
        }
    }
    
    /// <remarks/>
    public RP14InsolvencyDetails InsolvencyDetails {
        get {
            return this.insolvencyDetailsField;
        }
        set {
            this.insolvencyDetailsField = value;
        }
    }
    
    /// <remarks/>
    public RP14TransferDetails TransferDetails {
        get {
            return this.transferDetailsField;
        }
        set {
            this.transferDetailsField = value;
        }
    }
    
    /// <remarks/>
    public RP14PayRecordsContact PayRecordsContact {
        get {
            return this.payRecordsContactField;
        }
        set {
            this.payRecordsContactField = value;
        }
    }
    
    /// <remarks/>
    public RP14InsolvencyPractitioner InsolvencyPractitioner {
        get {
            return this.insolvencyPractitionerField;
        }
        set {
            this.insolvencyPractitionerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public partial class RP14Header {
    
    private string caseReferenceField;
    
    private string dMSDocumentIDField;
    
    private string claimReferenceField;
    
    private string cHAMPDocumentIDField;
    
    private string sourceField;
    
    private string externalReferenceField;
    
    public string CaseReference {
        get {
            return this.caseReferenceField;
        }
        set {
            this.caseReferenceField = value;
        }
    }
    
    /// <remarks/>
    public string DMSDocumentID {
        get {
            return this.dMSDocumentIDField;
        }
        set {
            this.dMSDocumentIDField = value;
        }
    }
    
    /// <remarks/>
    public string ClaimReference {
        get {
            return this.claimReferenceField;
        }
        set {
            this.claimReferenceField = value;
        }
    }
    
    /// <remarks/>
    public string CHAMPDocumentID {
        get {
            return this.cHAMPDocumentIDField;
        }
        set {
            this.cHAMPDocumentIDField = value;
        }
    }
    
    /// <remarks/>
    public string Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    public string ExternalReference {
        get {
            return this.externalReferenceField;
        }
        set {
            this.externalReferenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public partial class InsolvencyPractitionerType {
    
    private string registrationNumberField;
    
    private string firmNameField;
    
    private string nameField;
    
    private AddressType addressField;
    
    private string telephoneNumberField;
    
    private string emailAddressField;
    
    /// <remarks/>
    public string RegistrationNumber {
        get {
            return this.registrationNumberField;
        }
        set {
            this.registrationNumberField = value;
        }
    }
    
    /// <remarks/>
    public string FirmName {
        get {
            return this.firmNameField;
        }
        set {
            this.firmNameField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public AddressType Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public string TelephoneNumber {
        get {
            return this.telephoneNumberField;
        }
        set {
            this.telephoneNumberField = value;
        }
    }
    
    /// <remarks/>
    public string EmailAddress {
        get {
            return this.emailAddressField;
        }
        set {
            this.emailAddressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public partial class AddressType {
    
    private string[] lineField;
    
    private string townField;
    
    private string countyField;
    
    private string postcodeField;
    
    private string countryField;
    
    [System.Xml.Serialization.XmlElementAttribute("Line")]
    public string[] Line {
        get {
            return this.lineField;
        }
        set {
            this.lineField = value;
        }
    }
    
    public string Town {
        get {
            return this.townField;
        }
        set {
            this.townField = value;
        }
    }
    
    public string County {
        get {
            return this.countyField;
        }
        set {
            this.countyField = value;
        }
    }
    
    public string Postcode {
        get {
            return this.postcodeField;
        }
        set {
            this.postcodeField = value;
        }
    }
    
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public partial class NameType {
    
    private string surnameField;
    
    private string forenamesField;
    
    private string titleField;
    
    private string fullNameField;
    
    private string initialsField;
    
    /// <remarks/>
    public string Surname {
        get {
            return this.surnameField;
        }
        set {
            this.surnameField = value;
        }
    }
    
    /// <remarks/>
    public string Forenames {
        get {
            return this.forenamesField;
        }
        set {
            this.forenamesField = value;
        }
    }
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string FullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
    
    /// <remarks/>
    public string Initials {
        get {
            return this.initialsField;
        }
        set {
            this.initialsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public partial class PayeType {
    
    private string districtField;
    
    private string referenceField;
    
    /// <remarks/>
    public string District {
        get {
            return this.districtField;
        }
        set {
            this.districtField = value;
        }
    }
    
    /// <remarks/>
    public string Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public partial class RP14Directors {
    
    private RP14DirectorsDirector[] directorField;
    
    private YesNoType claimingRPAsEmployeeField;
    
    private bool claimingRPAsEmployeeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Director")]
    public RP14DirectorsDirector[] Director {
        get {
            return this.directorField;
        }
        set {
            this.directorField = value;
        }
    }
    
    /// <remarks/>
    public YesNoType ClaimingRPAsEmployee {
        get {
            return this.claimingRPAsEmployeeField;
        }
        set {
            this.claimingRPAsEmployeeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ClaimingRPAsEmployeeSpecified {
        get {
            return this.claimingRPAsEmployeeFieldSpecified;
        }
        set {
            this.claimingRPAsEmployeeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public partial class RP14DirectorsDirector {
    
    private NameType nameField;
    
    private string nINOField;
    
    /// <remarks/>
    public NameType Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    public string NINO {
        get {
            return this.nINOField;
        }
        set {
            this.nINOField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public enum YesNoType {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public partial class RP14Shareholder {
    
    private NameType nameField;
    
    private string noOfSharesHeldField;
    
    private decimal percentageField;
    
    private bool percentageFieldSpecified;
    
    /// <remarks/>
    public NameType Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NoOfSharesHeld {
        get {
            return this.noOfSharesHeldField;
        }
        set {
            this.noOfSharesHeldField = value;
        }
    }
    
    public decimal Percentage {
        get {
            return this.percentageField;
        }
        set {
            this.percentageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PercentageSpecified {
        get {
            return this.percentageFieldSpecified;
        }
        set {
            this.percentageFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public partial class RP14AssociatedCompanies {
    
    private YesNoType legallyAssociatedCompaniesField;
    
    private bool legallyAssociatedCompaniesFieldSpecified;
    
    private RP14AssociatedCompaniesAssociatedCompany[] associatedCompanyField;
    
    /// <remarks/>
    public YesNoType LegallyAssociatedCompanies {
        get {
            return this.legallyAssociatedCompaniesField;
        }
        set {
            this.legallyAssociatedCompaniesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LegallyAssociatedCompaniesSpecified {
        get {
            return this.legallyAssociatedCompaniesFieldSpecified;
        }
        set {
            this.legallyAssociatedCompaniesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AssociatedCompany")]
    public RP14AssociatedCompaniesAssociatedCompany[] AssociatedCompany {
        get {
            return this.associatedCompanyField;
        }
        set {
            this.associatedCompanyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public partial class RP14AssociatedCompaniesAssociatedCompany {
    
    private string companyNameField;
    
    private string companyNumberField;
    
    private AddressType addressField;
    
    private RP14AssociatedCompaniesAssociatedCompanyOfferToEmployEmployees offerToEmployEmployeesField;
    
    private string reasonForAssociationField;
    
    public string CompanyName {
        get {
            return this.companyNameField;
        }
        set {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyNumber {
        get {
            return this.companyNumberField;
        }
        set {
            this.companyNumberField = value;
        }
    }
    
    /// <remarks/>
    public AddressType Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public RP14AssociatedCompaniesAssociatedCompanyOfferToEmployEmployees OfferToEmployEmployees {
        get {
            return this.offerToEmployEmployeesField;
        }
        set {
            this.offerToEmployEmployeesField = value;
        }
    }
    
    public string ReasonForAssociation {
        get {
            return this.reasonForAssociationField;
        }
        set {
            this.reasonForAssociationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public partial class RP14AssociatedCompaniesAssociatedCompanyOfferToEmployEmployees {
    
    private YesNoType offerMadeField;
    
    private RP14AssociatedCompaniesAssociatedCompanyOfferToEmployEmployeesEmployee[] detailsOfOfferField;
    
    /// <remarks/>
    public YesNoType OfferMade {
        get {
            return this.offerMadeField;
        }
        set {
            this.offerMadeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Employee", IsNullable=false)]
    public RP14AssociatedCompaniesAssociatedCompanyOfferToEmployEmployeesEmployee[] DetailsOfOffer {
        get {
            return this.detailsOfOfferField;
        }
        set {
            this.detailsOfOfferField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public partial class RP14AssociatedCompaniesAssociatedCompanyOfferToEmployEmployeesEmployee {
    
    private System.DateTime dateAndTimeOfOfferField;
    
    private NameType nameField;
    
    private RP14AssociatedCompaniesAssociatedCompanyOfferToEmployEmployeesEmployeeOfferFormat offerFormatField;
    
    private RP14AssociatedCompaniesAssociatedCompanyOfferToEmployEmployeesEmployeeOfferMadeBy offerMadeByField;
    
    /// <remarks/>
    public System.DateTime DateAndTimeOfOffer {
        get {
            return this.dateAndTimeOfOfferField;
        }
        set {
            this.dateAndTimeOfOfferField = value;
        }
    }
    
    /// <remarks/>
    public NameType Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public RP14AssociatedCompaniesAssociatedCompanyOfferToEmployEmployeesEmployeeOfferFormat OfferFormat {
        get {
            return this.offerFormatField;
        }
        set {
            this.offerFormatField = value;
        }
    }
    
    /// <remarks/>
    public RP14AssociatedCompaniesAssociatedCompanyOfferToEmployEmployeesEmployeeOfferMadeBy OfferMadeBy {
        get {
            return this.offerMadeByField;
        }
        set {
            this.offerMadeByField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public enum RP14AssociatedCompaniesAssociatedCompanyOfferToEmployEmployeesEmployeeOfferFormat {
    
    /// <remarks/>
    oral,
    
    /// <remarks/>
    written,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public partial class RP14AssociatedCompaniesAssociatedCompanyOfferToEmployEmployeesEmployeeOfferMadeBy {
    
    private NameType nameField;
    
    private string positionInCompanyField;
    
    /// <remarks/>
    public NameType Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string PositionInCompany {
        get {
            return this.positionInCompanyField;
        }
        set {
            this.positionInCompanyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public partial class RP14Employees {
    
    private string noOfEmployeesField;
    
    private RP14EmployeesEmployeesClaimingContinuity employeesClaimingContinuityField;
    
    private YesNoType strikesField;
    
    private bool strikesFieldSpecified;
    
    private YesNoType carryOverHolidayEntitlementField;
    
    private bool carryOverHolidayEntitlementFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NoOfEmployees {
        get {
            return this.noOfEmployeesField;
        }
        set {
            this.noOfEmployeesField = value;
        }
    }
    
    /// <remarks/>
    public RP14EmployeesEmployeesClaimingContinuity EmployeesClaimingContinuity {
        get {
            return this.employeesClaimingContinuityField;
        }
        set {
            this.employeesClaimingContinuityField = value;
        }
    }
    
    /// <remarks/>
    public YesNoType Strikes {
        get {
            return this.strikesField;
        }
        set {
            this.strikesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StrikesSpecified {
        get {
            return this.strikesFieldSpecified;
        }
        set {
            this.strikesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public YesNoType CarryOverHolidayEntitlement {
        get {
            return this.carryOverHolidayEntitlementField;
        }
        set {
            this.carryOverHolidayEntitlementField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CarryOverHolidayEntitlementSpecified {
        get {
            return this.carryOverHolidayEntitlementFieldSpecified;
        }
        set {
            this.carryOverHolidayEntitlementFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public partial class RP14EmployeesEmployeesClaimingContinuity {
    
    private YesNoType claimingContinuityField;
    
    private bool claimingContinuityFieldSpecified;
    
    private string employerNameField;
    
    private AddressType addressField;
    
    private System.DateTime tradingDateField;
    
    private bool tradingDateFieldSpecified;
    
    private YesNoType shouldClaimsBeAcceptedField;
    
    private bool shouldClaimsBeAcceptedFieldSpecified;
    
    /// <remarks/>
    public YesNoType ClaimingContinuity {
        get {
            return this.claimingContinuityField;
        }
        set {
            this.claimingContinuityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ClaimingContinuitySpecified {
        get {
            return this.claimingContinuityFieldSpecified;
        }
        set {
            this.claimingContinuityFieldSpecified = value;
        }
    }
    
    public string EmployerName {
        get {
            return this.employerNameField;
        }
        set {
            this.employerNameField = value;
        }
    }
    
    /// <remarks/>
    public AddressType Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime TradingDate {
        get {
            return this.tradingDateField;
        }
        set {
            this.tradingDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TradingDateSpecified {
        get {
            return this.tradingDateFieldSpecified;
        }
        set {
            this.tradingDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public YesNoType ShouldClaimsBeAccepted {
        get {
            return this.shouldClaimsBeAcceptedField;
        }
        set {
            this.shouldClaimsBeAcceptedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ShouldClaimsBeAcceptedSpecified {
        get {
            return this.shouldClaimsBeAcceptedFieldSpecified;
        }
        set {
            this.shouldClaimsBeAcceptedFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public partial class RP14InsolvencyDetails {
    
    private System.DateTime insolvencyDateField;
    
    private bool insolvencyDateFieldSpecified;
    
    private string insolvencyTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime InsolvencyDate {
        get {
            return this.insolvencyDateField;
        }
        set {
            this.insolvencyDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InsolvencyDateSpecified {
        get {
            return this.insolvencyDateFieldSpecified;
        }
        set {
            this.insolvencyDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string InsolvencyType {
        get {
            return this.insolvencyTypeField;
        }
        set {
            this.insolvencyTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public partial class RP14TransferDetails {
    
    private RP14TransferDetailsTransferType transferTypeField;
    
    private bool transferTypeFieldSpecified;
    
    private RP14TransferDetailsTransferTo transferToField;
    
    private System.DateTime transferDateField;
    
    private bool transferDateFieldSpecified;
    
    private System.DateTime negotiationDateField;
    
    private bool negotiationDateFieldSpecified;
    
    /// <remarks/>
    public RP14TransferDetailsTransferType TransferType {
        get {
            return this.transferTypeField;
        }
        set {
            this.transferTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TransferTypeSpecified {
        get {
            return this.transferTypeFieldSpecified;
        }
        set {
            this.transferTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public RP14TransferDetailsTransferTo TransferTo {
        get {
            return this.transferToField;
        }
        set {
            this.transferToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime TransferDate {
        get {
            return this.transferDateField;
        }
        set {
            this.transferDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TransferDateSpecified {
        get {
            return this.transferDateFieldSpecified;
        }
        set {
            this.transferDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime NegotiationDate {
        get {
            return this.negotiationDateField;
        }
        set {
            this.negotiationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NegotiationDateSpecified {
        get {
            return this.negotiationDateFieldSpecified;
        }
        set {
            this.negotiationDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public enum RP14TransferDetailsTransferType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("asset only")]
    assetonly,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("whole business")]
    wholebusiness,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("part of business")]
    partofbusiness,
    
    /// <remarks/>
    other,
    
    /// <remarks/>
    none,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public partial class RP14TransferDetailsTransferTo {
    
    private string nameField;
    
    private AddressType addressField;
    
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public AddressType Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public partial class RP14PayRecordsContact {
    
    private string nameField;
    
    private AddressType addressField;
    
    private string phoneNumberField;
    
    private string emailAddressField;
    
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public AddressType Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    public string PhoneNumber {
        get {
            return this.phoneNumberField;
        }
        set {
            this.phoneNumberField = value;
        }
    }
    
    /// <remarks/>
    public string EmailAddress {
        get {
            return this.emailAddressField;
        }
        set {
            this.emailAddressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="www.inss.gsi.gov.uk/RP14_Application")]
public partial class RP14InsolvencyPractitioner : InsolvencyPractitionerType {
    
    private bool declarationAgreementField;
    
    /// <remarks/>
    public bool DeclarationAgreement {
        get {
            return this.declarationAgreementField;
        }
        set {
            this.declarationAgreementField = value;
        }
    }
}