CREATE TABLE [dbo].[Address]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[InstanceId] UNIQUEIDENTIFIER NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[AddressLine1] NVARCHAR(255) NOT NULL,
	[AddressLine2] NVARCHAR(255) NULL,
	[TownCity] NVARCHAR(100) NOT NULL,
	[County] NVARCHAR(100) NULL,
	[Postcode] NVARCHAR(20) NOT NULL,
	[Created] DATETIME2 NOT NULL,
	[CreatedBy] NVARCHAR(255) NOT NULL,
	[Modified] DATETIME2 NULL,
	[ModifiedBy] NVARCHAR(255) NULL,
	CONSTRAINT [PK_Address] PRIMARY KEY CLUSTERED 
	(
		[Id]
	) 
)

GO

ALTER TABLE [dbo].[Address] ADD CONSTRAINT [FK_Address_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Address] CHECK CONSTRAINT [FK_Address_User]
GO

ALTER TABLE [dbo].[Address]
ADD CONSTRAINT [DF_Address_Created] DEFAULT (GETUTCDATE()) FOR [Created];
GO