CREATE TABLE [dbo].[User]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[InstanceId] UNIQUEIDENTIFIER NOT NULL,
	[FullName] NVARCHAR(255) NOT NULL,
	[DateOfBirth] DATE NOT NULL,
	[TelephoneNumber] NVARCHAR(20) NOT NULL,
	[EmailAddress] NVARCHAR(255) NOT NULL,
	[Created] DATETIME2 NOT NULL,
	[CreatedBy] NVARCHAR(255) NOT NULL,
	[Modified] DATETIME2 NULL,
	[ModifiedBy] NVARCHAR(255) NULL,
	CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
	(
		[Id]
	) 
)
GO

ALTER TABLE [dbo].[User]
ADD CONSTRAINT [DF_User_Created] DEFAULT (GETUTCDATE()) FOR [Created];
GO
