//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Schema: https://github.com/InsolvencyService/RedundancyUploadService/blob/develop/Insolvency.RedundancyUploadService.Common/Models/Schemas/RP14A.xsd

using System.ComponentModel.DataAnnotations;
using Inss.GovUk.Forms.IPUpload.Domain.Validation;
using Inss.GovUk.Forms.IPUpload.Domain.Validation.Attributes;

namespace Inss.GovUk.Forms.IPUpload.Domain.Api;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.inss.gsi.gov.uk/RP14A_Application")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "www.inss.gsi.gov.uk/RP14A_Application", IsNullable = false)]
public partial class RP14A
{

    private RP14AHeader headerField;

    private string employerNameField;

    private RP14AEmployee[] employeeField;

    /// <remarks/>
    public RP14AHeader Header
    {
        get
        {
            return this.headerField;
        }
        set
        {
            this.headerField = value;
        }
    }

    /// <remarks/>
    [StringLengthProperty("InvalidLengthEmployerName", 99)]
    public string EmployerName
    {
        get
        {
            return this.employerNameField;
        }
        set
        {
            this.employerNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Employee")]
    public RP14AEmployee[] Employee
    {
        get
        {
            return this.employeeField;
        }
        set
        {
            this.employeeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.inss.gsi.gov.uk/RP14A_Application")]
public partial class RP14AHeader
{

    private string caseReferenceField;

    private string dMSDocumentIDField;

    private string claimReferenceField;

    private string cHAMPDocumentIDField;

    /// <remarks/>
    [CaseReference("UnknownCaseReference")]
    [RequiredProperty("MissingCaseReference")]
    [RegularExpressionProperty("InvalidFormatCaseReference", "CN[0-9]{8}|cn[0-9]{8}|Cn[0-9]{8}|cN[0-9]{8}")]
    [StringLengthProperty("InvalidLengthCaseReference", 12)]
    public string CaseReference
    {
        get
        {
            return this.caseReferenceField;
        }
        set
        {
            this.caseReferenceField = value;
        }
    }

    /// <remarks/>
    public string DMSDocumentID
    {
        get
        {
            return this.dMSDocumentIDField;
        }
        set
        {
            this.dMSDocumentIDField = value;
        }
    }

    /// <remarks/>
    public string ClaimReference
    {
        get
        {
            return this.claimReferenceField;
        }
        set
        {
            this.claimReferenceField = value;
        }
    }

    /// <remarks/>
    public string CHAMPDocumentID
    {
        get
        {
            return this.cHAMPDocumentIDField;
        }
        set
        {
            this.cHAMPDocumentIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "www.inss.gsi.gov.uk/RP14A_Application")]
public partial class PeriodType
{

    private System.DateTime startDateField;

    private System.DateTime endDateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime StartDate
    {
        get
        {
            return this.startDateField;
        }
        set
        {
            this.startDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime EndDate
    {
        get
        {
            return this.endDateField;
        }
        set
        {
            this.endDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "www.inss.gsi.gov.uk/RP14A_Application")]
public partial class NameType
{

    private string surnameField;

    private string forenamesField;

    private string titleField;

    /// <remarks/>
    [RequiredProperty("MissingEmployeeSurname")]
    [StringLengthProperty("InvalidLengthEmployeeSurname", 99)]
    public string Surname
    {
        get
        {
            return this.surnameField;
        }
        set
        {
            this.surnameField = value;
        }
    }

    /// <remarks/>
    public string Forenames
    {
        get
        {
            return this.forenamesField;
        }
        set
        {
            this.forenamesField = value;
        }
    }

    /// <remarks/>
    public string Title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.inss.gsi.gov.uk/RP14A_Application")]
public partial class RP14AEmployee : IValidatableObject
{

    private NameType employeeNameField;

    private string nIClassField;

    private string nINOField;

    private System.DateTime dateOfBirthField;

    private bool dateOfBirthFieldSpecified;

    private System.DateTime startDateField;

    private bool startDateFieldSpecified;

    private System.DateTime dateNoticeGivenField;

    private bool dateNoticeGivenFieldSpecified;

    private System.DateTime endDateField;

    private bool endDateFieldSpecified;

    private YesNoType isDirectorField;

    private bool isDirectorFieldSpecified;

    private decimal averageHoursWorkedField;

    private bool averageHoursWorkedFieldSpecified;

    private decimal MoneyOwedToEmployerField;

    private bool MoneyOwedToEmployerFieldSpecified;

    private YesNoType entitledToRedundancyPayField;

    private bool entitledToRedundancyPayFieldSpecified;

    private YesNoType entitledToNoticePayField;

    private bool entitledToNoticePayFieldSpecified;

    private RP14AEmployeePayDetails payDetailsField;

    private RP14AEmployeeHoliday holidayField;

    /// <remarks/>
    public NameType EmployeeName
    {
        get
        {
            return this.employeeNameField;
        }
        set
        {
            this.employeeNameField = value;
        }
    }

    /// <remarks/>
    public string NIClass
    {
        get
        {
            return this.nIClassField;
        }
        set
        {
            this.nIClassField = value;
        }
    }

    /// <remarks/>
    [RequiredProperty("MissingEmployeeNino")]
    [RegularExpressionProperty("InvalidFormatEmployeeNino", "[A-CEGHJ-PR-TW-Za-ceghj-pr-tw-z]{1}[A-CEGHJ-NPR-TW-Za-ceghj-npr-tw-z]{1}[0-9]{6}[A-DFMa-dfm]{1}")]
    public string NINO
    {
        get
        {
            return this.nINOField;
        }
        set
        {
            this.nINOField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime DateOfBirth
    {
        get
        {
            return this.dateOfBirthField;
        }
        set
        {
            this.dateOfBirthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DateOfBirthSpecified
    {
        get
        {
            return this.dateOfBirthFieldSpecified;
        }
        set
        {
            this.dateOfBirthFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime StartDate
    {
        get
        {
            return this.startDateField;
        }
        set
        {
            this.startDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StartDateSpecified
    {
        get
        {
            return this.startDateFieldSpecified;
        }
        set
        {
            this.startDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime DateNoticeGiven
    {
        get
        {
            return this.dateNoticeGivenField;
        }
        set
        {
            this.dateNoticeGivenField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DateNoticeGivenSpecified
    {
        get
        {
            return this.dateNoticeGivenFieldSpecified;
        }
        set
        {
            this.dateNoticeGivenFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime EndDate
    {
        get
        {
            return this.endDateField;
        }
        set
        {
            this.endDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EndDateSpecified
    {
        get
        {
            return this.endDateFieldSpecified;
        }
        set
        {
            this.endDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    public YesNoType IsDirector
    {
        get
        {
            return this.isDirectorField;
        }
        set
        {
            this.isDirectorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsDirectorSpecified
    {
        get
        {
            return this.isDirectorFieldSpecified;
        }
        set
        {
            this.isDirectorFieldSpecified = value;
        }
    }

    /// <remarks/>
    public decimal AverageHoursWorked
    {
        get
        {
            return this.averageHoursWorkedField;
        }
        set
        {
            this.averageHoursWorkedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AverageHoursWorkedSpecified
    {
        get
        {
            return this.averageHoursWorkedFieldSpecified;
        }
        set
        {
            this.averageHoursWorkedFieldSpecified = value;
        }
    }

    /// <remarks/>
    [RegularExpressionProperty("InvalidFormatMoneyOwedToEmployer", @"^\d+(\.\d{2})?$")]
    public decimal MoneyOwedToEmployer
    {
        get
        {
            return this.MoneyOwedToEmployerField;
        }
        set
        {
            this.MoneyOwedToEmployerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MoneyOwedToEmployerSpecified
    {
        get
        {
            return this.MoneyOwedToEmployerFieldSpecified;
        }
        set
        {
            this.MoneyOwedToEmployerFieldSpecified = value;
        }
    }

    /// <remarks/>
    public YesNoType EntitledToRedundancyPay
    {
        get
        {
            return this.entitledToRedundancyPayField;
        }
        set
        {
            this.entitledToRedundancyPayField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EntitledToRedundancyPaySpecified
    {
        get
        {
            return this.entitledToRedundancyPayFieldSpecified;
        }
        set
        {
            this.entitledToRedundancyPayFieldSpecified = value;
        }
    }

    /// <remarks/>
    public YesNoType EntitledToNoticePay
    {
        get
        {
            return this.entitledToNoticePayField;
        }
        set
        {
            this.entitledToNoticePayField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EntitledToNoticePaySpecified
    {
        get
        {
            return this.entitledToNoticePayFieldSpecified;
        }
        set
        {
            this.entitledToNoticePayFieldSpecified = value;
        }
    }

    /// <remarks/>
    public RP14AEmployeePayDetails PayDetails
    {
        get
        {
            return this.payDetailsField;
        }
        set
        {
            this.payDetailsField = value;
        }
    }

    /// <remarks/>
    public RP14AEmployeeHoliday Holiday
    {
        get
        {
            return this.holidayField;
        }
        set
        {
            this.holidayField = value;
        }
    }
    
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        if (StartDate > EndDate)
        {
            ValidationResult result = validationContext.CreateValidationResult(
                "EmploymentEndBeforeStartDate", 
                "EmploymentEndBeforeStartDate",
                [nameof(StartDate), nameof(EndDate)]);

            if (result is not null)
            {
                yield return result;
            }
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "www.inss.gsi.gov.uk/RP14A_Application")]
public enum YesNoType
{

    /// <remarks/>
    Yes,

    /// <remarks/>
    No,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.inss.gsi.gov.uk/RP14A_Application")]
public partial class RP14AEmployeePayDetails
{

    private decimal basicPayPerWeekField;

    private bool basicPayPerWeekFieldSpecified;

    private RP14AEmployeePayDetailsComponentPayPerWeek[] componentPayPerWeekField;

    private RP14AEmployeePayDetailsWeeklyPayDay weeklyPayDayField;

    private bool weeklyPayDayFieldSpecified;

    private RP14AEmployeePayDetailsArrearsOfPayPeriod[] arrearsOfPayField;

    /// <remarks/>
    [RegularExpressionProperty("InvalidFormatEmployeeBasicPayPerWeek", @"^\d+(\.\d{2})?$")]
    public decimal BasicPayPerWeek
    {
        get
        {
            return this.basicPayPerWeekField;
        }
        set
        {
            this.basicPayPerWeekField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BasicPayPerWeekSpecified
    {
        get
        {
            return this.basicPayPerWeekFieldSpecified;
        }
        set
        {
            this.basicPayPerWeekFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ComponentPayPerWeek")]
    public RP14AEmployeePayDetailsComponentPayPerWeek[] ComponentPayPerWeek
    {
        get
        {
            return this.componentPayPerWeekField;
        }
        set
        {
            this.componentPayPerWeekField = value;
        }
    }

    /// <remarks/>
    public RP14AEmployeePayDetailsWeeklyPayDay WeeklyPayDay
    {
        get
        {
            return this.weeklyPayDayField;
        }
        set
        {
            this.weeklyPayDayField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WeeklyPayDaySpecified
    {
        get
        {
            return this.weeklyPayDayFieldSpecified;
        }
        set
        {
            this.weeklyPayDayFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ArrearsOfPayPeriod", IsNullable = false)]
    public RP14AEmployeePayDetailsArrearsOfPayPeriod[] ArrearsOfPay
    {
        get
        {
            return this.arrearsOfPayField;
        }
        set
        {
            this.arrearsOfPayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.inss.gsi.gov.uk/RP14A_Application")]
public partial class RP14AEmployeePayDetailsComponentPayPerWeek
{

    private RP14AEmployeePayDetailsComponentPayPerWeekComponentType componentTypeField;

    private string componentRateField;

    private bool componentRateFieldSpecified;

    private RP14AEmployeePayDetailsComponentPayPerWeekComponentRateStatus componentRateStatusField;

    public RP14AEmployeePayDetailsComponentPayPerWeek()
    {
        this.componentRateStatusField = RP14AEmployeePayDetailsComponentPayPerWeekComponentRateStatus.Rateprovided;
    }

    /// <remarks/>
    public RP14AEmployeePayDetailsComponentPayPerWeekComponentType ComponentType
    {
        get
        {
            return this.componentTypeField;
        }
        set
        {
            this.componentTypeField = value;
        }
    }

    /// <remarks/>
    //[System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ComponentRate
    {
        get
        {
            return this.componentRateField;
        }
        set
        {
            this.componentRateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ComponentRateSpecified
    {
        get
        {
            return this.componentRateFieldSpecified;
        }
        set
        {
            this.componentRateFieldSpecified = value;
        }
    }


    /// <remarks/>
    public RP14AEmployeePayDetailsComponentPayPerWeekComponentRateStatus ComponentRateStatus
    {
        get
        {
            return this.componentRateStatusField;
        }
        set
        {
            this.componentRateStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.inss.gsi.gov.uk/RP14A_Application")]
public enum RP14AEmployeePayDetailsComponentPayPerWeekComponentType
{

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Redundancy Pay")]
    RedundancyPay,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Arrears of Pay")]
    ArrearsofPay,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Holiday Pay Taken Not Paid")]
    HolidayPayTakenNotPaid,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Holiday Pay Accrued")]
    HolidayPayAccrued,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Protective Award")]
    ProtectiveAward,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Compensatory Notice Pay")]
    CompensatoryNoticePay,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Refund of Notional Tax")]
    RefundofNotionalTax,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Basic Award")]
    BasicAward,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Notice Worked Not Paid")]
    NoticeWorkedNotPaid,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.inss.gsi.gov.uk/RP14A_Application")]
public enum RP14AEmployeePayDetailsComponentPayPerWeekComponentRateStatus
{
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("")]
    Default,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Rate provided")]
    Rateprovided,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("No rate defined in law")]
    Noratedefinedinlaw,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Data not yet available")]
    Datanotyetavailable,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Data to be requested from IP")]
    Datatoberequestedfromip,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Fixed rate of pay")]
    Fixedrateofpay,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("No holiday pay payable")]
    Noholidaypaypayable,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.inss.gsi.gov.uk/RP14A_Application")]
public enum RP14AEmployeePayDetailsWeeklyPayDay
{

    /// <remarks/>
    Sunday,

    /// <remarks/>
    Monday,

    /// <remarks/>
    Tuesday,

    /// <remarks/>
    Wednesday,

    /// <remarks/>
    Thursday,

    /// <remarks/>
    Friday,

    /// <remarks/>
    Saturday,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.inss.gsi.gov.uk/RP14A_Application")]
public partial class RP14AEmployeePayDetailsArrearsOfPayPeriod : IValidatableObject
{

    private PeriodType periodField;

    private decimal aOPOwedField;

    private bool aOPOwedFieldSpecified;

    private RP14AEmployeePayDetailsArrearsOfPayPeriodPayType payTypeField;

    private bool payTypeFieldSpecified;

    /// <remarks/>
    public PeriodType Period
    {
        get
        {
            return this.periodField;
        }
        set
        {
            this.periodField = value;
        }
    }

    /// <remarks/>
    [RegularExpressionProperty("InvalidFormatEmployeeAOP", @"^\d+(\.\d{2})?$")]
    public decimal AOPOwed
    {
        get
        {
            return this.aOPOwedField;
        }
        set
        {
            this.aOPOwedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AOPOwedSpecified
    {
        get
        {
            return this.aOPOwedFieldSpecified;
        }
        set
        {
            this.aOPOwedFieldSpecified = value;
        }
    }

    /// <remarks/>
    public RP14AEmployeePayDetailsArrearsOfPayPeriodPayType PayType
    {
        get
        {
            return this.payTypeField;
        }
        set
        {
            this.payTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PayTypeSpecified
    {
        get
        {
            return this.payTypeFieldSpecified;
        }
        set
        {
            this.payTypeFieldSpecified = value;
        }
    }
    
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        if (Period.StartDate > Period.EndDate)
        {
            ValidationResult result = validationContext.CreateValidationResult(
                "AOPEndBeforeStartDate", 
                "AOPEndBeforeStartDate",
                [nameof(Period.StartDate), nameof(Period.EndDate)]);

            if (result is not null)
            {
                yield return result;
            }
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.inss.gsi.gov.uk/RP14A_Application")]
public enum RP14AEmployeePayDetailsArrearsOfPayPeriodPayType
{

    /// <remarks/>
    wages,

    /// <remarks/>
    bouncedcheque,

    /// <remarks/>
    attachmentofearnings,

    /// <remarks/>
    overtime,

    /// <remarks/>
    commission,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.inss.gsi.gov.uk/RP14A_Application")]
public partial class RP14AEmployeeHoliday : IValidatableObject
{

    private System.DateTime holidayYearStartField;

    private bool holidayYearStartFieldSpecified;

    private decimal holidayContractedEntitlementDaysField;

    private bool holidayContractedEntitlementDaysFieldSpecified;

    private decimal holidayDaysCarriedForwardField;

    private bool holidayDaysCarriedForwardFieldSpecified;

    private decimal holidayDaysTakenField;

    private bool holidayDaysTakenFieldSpecified;

    private PeriodType[] holidayNotPaidField;

    private decimal noDaysHolidayOwedField;

    private bool noDaysHolidayOwedFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime HolidayYearStart
    {
        get { return this.holidayYearStartField; }
        set { this.holidayYearStartField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HolidayYearStartSpecified
    {
        get { return this.holidayYearStartFieldSpecified; }
        set { this.holidayYearStartFieldSpecified = value; }
    }

    /// <remarks/>
    [RequiredProperty("MissingContractedHolidayEntitlement")]
    [RegularExpressionProperty("InvalidContractedHolidayEntitlement", @"^\d+(\.\d{2})?$")]
    [RangeProperty("InvalidRangeContractedHolidayEntitlement", 0, 365)]
    public decimal HolidayContractedEntitlementDays
    {
        get { return this.holidayContractedEntitlementDaysField; }
        set { this.holidayContractedEntitlementDaysField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HolidayContractedEntitlementDaysSpecified
    {
        get { return this.holidayContractedEntitlementDaysFieldSpecified; }
        set { this.holidayContractedEntitlementDaysFieldSpecified = value; }
    }

    /// <remarks/>
    [RequiredProperty("MissingHolidayCarriedForward")]
    [RegularExpressionProperty("InvalidHolidayCarriedForward", @"^\d+(\.\d{2})?$")]
    [RangeProperty("InvalidRangeHolidayCarriedForward", 0, 365)]
    public decimal HolidayDaysCarriedForward
    {
        get { return this.holidayDaysCarriedForwardField; }
        set { this.holidayDaysCarriedForwardField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HolidayDaysCarriedForwardSpecified
    {
        get { return this.holidayDaysCarriedForwardFieldSpecified; }
        set { this.holidayDaysCarriedForwardFieldSpecified = value; }
    }

    /// <remarks/>
    [RequiredProperty("MissingHolidayTaken")]
    [RegularExpressionProperty("InvalidHolidayTaken", @"^\d+(\.\d{2})?$")]
    [RangeProperty("InvalidRangeHolidayTaken", 0, 365)]
    public decimal HolidayDaysTaken
    {
        get { return this.holidayDaysTakenField; }
        set { this.holidayDaysTakenField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HolidayDaysTakenSpecified
    {
        get { return this.holidayDaysTakenFieldSpecified; }
        set { this.holidayDaysTakenFieldSpecified = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Holiday", IsNullable = false)]
    public PeriodType[] HolidayNotPaid
    {
        get { return this.holidayNotPaidField; }
        set { this.holidayNotPaidField = value; }
    }

    /// <remarks/>
    [RequiredProperty("MissingHolidayOwed")]
    [RegularExpressionProperty("InvalidHolidayOwed", @"^\d+(\.\d{2})?$")]
    [RangeProperty("InvalidRangeHolidayOwed", 0, 365)]
    public decimal NoDaysHolidayOwed
    {
        get { return this.noDaysHolidayOwedField; }
        set { this.noDaysHolidayOwedField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NoDaysHolidayOwedSpecified
    {
        get { return this.noDaysHolidayOwedFieldSpecified; }
        set { this.noDaysHolidayOwedFieldSpecified = value; }
    }
    
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        for (int i = 0; i < HolidayNotPaid.Length; i++)
        {
            if (HolidayNotPaid[i].StartDate > HolidayNotPaid[i].EndDate)
            {
                ValidationResult result = validationContext.CreateValidationResult(
                    "HolidayNotPaidEndBeforeStartDate",
                    $"HolidayNotPaidEndBeforeStartDate{i}",
                    [nameof(HolidayNotPaid)]);

                if (result is not null)
                {
                    yield return result;
                }
            }
        }
    }
}