parameters:
  - name: environment
    type: string
    default: 'Dev'
  - name: location
    type: string
    default: 'uksouth'
  - name: azureSubscription
    type: string
    
jobs:
  - deployment:
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureRmWebAppDeployment@4
              displayName: Azure Web App Deploy
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: ${{ parameters.azureSubscription }}
                appType: 'webApp'
                WebAppName: 'app-ipupload-${{ lower(parameters.environment) }}'
                resourceGroupName: 'rg-platform-temp' #'rg-platform-${{ lower(parameters.environment) }}'
                package: '$(Pipeline.Workspace)/**/GovUk.Forms.HostApp.zip'
                deployToSlotOrASE: false
                slotName: 'production'
                appSettings: >
                  -DOTNET_HOSTINGSTARTUPASSEMBLIES "GovUk.Forms.Components;GovUk.Forms.HostApp;Inss.GovUk.Forms.IPUpload"
                  -APPLICATIONINSIGHTS_CONNECTION_STRING "InstrumentationKey=your-key-here"
                  -Broker__JwtPublicKey "-----BEGIN PUBLIC KEY----- MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtkw6a1gJg95FMaDBbET8 Yfdk9P1Pl7DMKok+868r7g2V9BuwbwoSjIBGXAqJuWoYX6NChkjHvO9dKTWHTqpg C0wDwNFdp6QGEZpqPj2n6PTGTyUpTJttf4AHr9sVDIhCe5aEipBVcbrApIsShSy7 /US763a7T/BLpyhZVaysgnUE19P7zM91Ehqf0vPlT0QjHQsHw3E2x7vr4J9NZjIM OoBlwL910KZra6g7Bwh1jGY9GDCiON0DnZkjp5BzxMsBHrI3lFBZHXNKbpfRZrWY RuaUaxHOSt2OI0nrd2i9ZCARXPmyHOfkskZT5GUy8wiGjA7mtF8pOIsHgKMDrjyW pwIDAQAB -----END PUBLIC KEY-----"

            #- task: AzureAppServiceSettings@1
            #  displayName: Apply App Service Settings
            #  inputs:
            #    azureSubscription: ${{ parameters.azureSubscription }}
            #    appName: 'app-${{ parameters.location }}-${{ lower(parameters.environment) }}'
            #    slotName: 'staging'
            #    appSettings: |
            #      [
            #        {
            #            "name": "Environment",
            #            "value": "${{ parameters.environment }}",
            #            "slotSetting": false
            #        }
            #      ]

            #- task: AzureAppServiceManage@0
            #  displayName: Start Staging Slot
            #  inputs:
            #    azureSubscription: ${{ parameters.azureSubscription }}
            #    Action: 'Start Azure App Service'
            #    WebAppName: 'app-ipupload-${{ lower(parameters.environment) }}'
            #    resourceGroupName: 'rg-platform-temp' #'rg-platform-${{ lower(parameters.environment) }}'
            #    SpecifySlotOrASE: true
            #    Slot: 'staging'

            #- task: AzureAppServiceManage@0
            #  displayName: Start Production Slot
            #  inputs:
            #    azureSubscription: ${{ parameters.azureSubscription }}
            #    Action: 'Start Azure App Service'
            #    WebAppName: 'app-ipupload-${{ lower(parameters.environment) }}'
            #    resourceGroupName: 'rg-platform-temp' #'rg-dsp-prototype' #'rg-platform-${{ lower(parameters.environment) }}'
            #    SpecifySlotOrASE: true
            #    Slot: 'Production'

            #- task: PowerShell@2
            #  displayName: 'Performing Health Check - Staging'
            #  inputs:
            #    failOnStderr: true
            #    targetType: 'filePath'
            #    filePath: $(System.DefaultWorkingDirectory)/powershell/InvokeRequestWithRetry.ps1
            #    arguments: > # Use this to avoid newline characters in multi-line string
            #      -URI "https://app-ipupload-${{ lower(parameters.environment) }}-staging.azurewebsites.net/"
            #      -Method "${{ parameters.method }}"
            #      -Retries ${{ parameters.retries }}
            #      -SecondsDelay ${{ parameters.secondsDelay }}
            #      -TimeoutSec ${{ parameters.timeoutSec }}

            #- task: AzureAppServiceManage@0
            #  displayName: Swap Staging Slot into Production
            #  inputs:
            #    azureSubscription: ${{ parameters.azureSubscription }}
            #    Action: 'Swap Slots'
            #    WebAppName: 'app-ipupload-${{ lower(parameters.environment) }}'
            #    resourceGroupName: 'rg-platform-temp' #'rg-platform-${{ lower(parameters.environment) }}'
            #    SourceSlot: 'staging'
            #    SwapWithProduction: true
            
            ##          - task: PowerShell@2
            ##            displayName: 'Performing Health Check - Production'
            ##            inputs:
            ##              failOnStderr: true
            ##              targetType: 'filePath'
            ##              filePath: $(System.DefaultWorkingDirectory)/powershell/InvokeRequestWithRetry.ps1
            ##              arguments: > # Use this to avoid newline characters in multi-line string
            ##                -URI "https://app-${{ parameters.location }}-${{ lower(parameters.environment) }}-ce-calcengine.azurewebsites.net/api/health/ping"
            ##                -Method "${{ parameters.method }}"
            ##                -Retries ${{ parameters.retries }}
            ##                -SecondsDelay ${{ parameters.secondsDelay }}
            ##                -TimeoutSec ${{ parameters.timeoutSec }}

            # TODO: Fails
            #- task: AzureAppServiceManage@0
            #  displayName: Stop Staging Slot
            #  inputs:
            #    azureSubscription: ${{ parameters.azureSubscription }}
            #    Action: 'Stop Azure App Service'