parameters:
  - name: environment
    type: string
    default: 'Dev'
  - name: location
    type: string
  - name: azureSubscription
    type: string
    
jobs:
  - deployment:
    variables:
      resourceGroupName: rg-platform-${{ parameters.location }}-${{ lower(parameters.environment) }}
      ipUploadAppName: app-ipupload-${{ parameters.location }}-${{ lower(parameters.environment) }}
      brokerAppName: app-broker-${{ parameters.location }}-${{ lower(parameters.environment) }}
      rpsAppName: app-rps-${{ parameters.location }}-${{ lower(parameters.environment) }}
      submissionAppName: app-submission-${{ parameters.location }}-${{ lower(parameters.environment) }}
      fipAppName: app-fip-${{ parameters.location }}-${{ lower(parameters.environment) }}
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureRmWebAppDeployment@4
              displayName: Deploy RPS Provider Service
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: ${{ parameters.azureSubscription }}
                appType: 'webApp'
                WebAppName: ${{ variables.rpsAppName }}
                resourceGroupName: ${{ variables.resourceGroupName }}
                package: '$(Pipeline.Workspace)/**/Inss.Platform.RpsProvider.zip'
                deployToSlotOrASE: false
                slotName: 'production'
            
            - task: AzureRmWebAppDeployment@4
              displayName: Deploy Broker Service
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: ${{ parameters.azureSubscription }}
                appType: 'webApp'
                WebAppName: ${{ variables.brokerAppName }}
                resourceGroupName: ${{ variables.resourceGroupName }}
                package: '$(Pipeline.Workspace)/**/Inss.Platform.Broker.zip'
                deployToSlotOrASE: false
                slotName: 'production'

            - task: AzureRmWebAppDeployment@4
              displayName: Deploy IP Upload App
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: ${{ parameters.azureSubscription }}
                appType: 'webApp'
                WebAppName: ${{ variables.ipUploadAppName }}
                resourceGroupName: ${{ variables.resourceGroupName }}
                package: '$(Pipeline.Workspace)/**/Inss.Platform.Ipus.zip'
                deployToSlotOrASE: false
                slotName: 'production'

            - task: AzureRmWebAppDeployment@4
              displayName: Deploy Submission Service
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: ${{ parameters.azureSubscription }}
                appType: 'webApp'
                WebAppName: ${{ variables.submissionAppName }}
                resourceGroupName: ${{ variables.resourceGroupName }}
                package: '$(Pipeline.Workspace)/**/Inss.Platform.Submission.Service.zip'
                deployToSlotOrASE: false
                slotName: 'production'

            - task: AzureRmWebAppDeployment@4
              displayName: Deploy FIP App
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: ${{ parameters.azureSubscription }}
                appType: 'webApp'
                WebAppName: ${{ variables.fipAppName }}
                resourceGroupName: ${{ variables.resourceGroupName }}
                package: '$(Pipeline.Workspace)/**/Inss.Platform.Fip.zip'
                deployToSlotOrASE: false
                slotName: 'production'