CREATE TABLE [dbo].[Product]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(512) NOT NULL,
	[Url] NVARCHAR(2083) NULL,
	[Created] DATETIME2 NOT NULL,
	[CreatedBy] NVARCHAR(255) NOT NULL,
	[Modified] DATETIME2 NULL,
	[ModifiedBy] NVARCHAR(255) NULL,
	CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
	(
		[Id]
	) 
)
GO

ALTER TABLE [dbo].[Product]
ADD CONSTRAINT [UQ_Product_Name] UNIQUE ([Name]);
GO

ALTER TABLE [dbo].[Product]
ADD CONSTRAINT [DF_Product_Created] DEFAULT (GETUTCDATE()) FOR [Created];
GO
