CREATE TABLE [dbo].[Resource]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(512) NOT NULL,
	[Created] DATETIME2 NOT NULL,
	[CreatedBy] NVARCHAR(255) NOT NULL,
	[Modified] DATETIME2 NULL,
	[ModifiedBy] NVARCHAR(255) NULL,
	CONSTRAINT [PK_Resource] PRIMARY KEY CLUSTERED 
	(
		[Id]
	) 
)
GO

ALTER TABLE [dbo].[Resource]
ADD CONSTRAINT [UQ_Resource_Name] UNIQUE ([Name]);
GO

ALTER TABLE [dbo].[Resource]
ADD CONSTRAINT [DF_Resource_Created] DEFAULT (GETUTCDATE()) FOR [Created];
GO
