//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Text.Json.Serialization;

namespace Inss.FormsSubmission.Service.IPUpload.Employer;

public sealed class Director 
{
    [JsonPropertyName("surname")]
    public string Surname { get; init; }

    [JsonPropertyName("initials")]
    public string Initials { get; init; }

    [JsonPropertyName("national_insurance_number")]
    public string NationalInsuranceNumber { get; init; }
}