//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Text.Json.Serialization;

namespace Inss.FormsSubmission.Service.IPUpload.Employer;

public sealed class TransferTo
{
    [JsonPropertyName("name")]
    public string Name { get; init; }

    [JsonPropertyName("address")]
    public Address Address { get; init; }

    [JsonPropertyName("transfer_date")]
    public DateTime? TransferDate { get; init; }

    [JsonPropertyName("date_negotiation_began")]
    public DateTime? DateNegotiationBegan { get; init; }
}